import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { useSelector } from "react-redux";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { citizenshipApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const empty = () => ({ name: "", description: "" });
const rowsOf = (r) => Array.isArray(r?.data) ? r.data : r?.data?.data ?? r?.data?.citizenship_array ?? [];
const idOf = (r) => r?.id ?? r?.citizenship_id;
const allowed = (menus, action) => (menus ?? []).some((m) => /citizenship/i.test(String(m?.menu_name)) && (m.actions ?? []).some((a) => { const n = String(a?.action_name ?? a?.name ?? "").toLowerCase(); return n === action.toLowerCase() || action === "Add" && n === "create" || action === "Authorize" && n === "authorise"; }));
function CitizenshipForm({ open, value, setValue, editing, saving, onClose, onSave }) { return <Modal open={open} onClose={onClose} title={editing ? "Edit citizenship" : "Add citizenship"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-slate-500">Cancel</button><button type="submit" form="citizenship-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Save as draft</button><button type="submit" form="citizenship-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">{saving ? "Saving..." : editing ? "Save changes" : "Add citizenship"}</button></>}><form id="citizenship-form" onSubmit={(e) => { e.preventDefault(); onSave(e.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Citizenship name<input required value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label></form></Modal>; }
export function Citizenship() {
  const menus = useSelector((s) => s.menu.menuArray); const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false);
  const can = (a) => allowed(menus, a); const load = useCallback(async () => { setLoading(true); try { const r = await citizenshipApi.list({ page, limit }); setRows(rowsOf(r)); setPagination(r?.pagination ?? r?.data?.pagination ?? {}); } catch (e) { notifications.error(e.message); } finally { setLoading(false); } }, [page, limit]); useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rows.filter((r) => (tab === "all" || statusBucket(r) === tab) && `${r.name ?? ""} ${r.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (isDraft) => { if (!form.name.trim()) return notifications.error("Citizenship name is required"); setSaving(true); try { const p = { ...form, is_draft: isDraft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const r = await (editing ? citizenshipApi.edit(p) : citizenshipApi.add(p)); notifications.success(apiMessage(r, "Citizenship saved")); setOpen(false); setEditing(null); setForm(empty()); void load(); } catch (e) { notifications.error(e.message); } finally { setSaving(false); } };
  const run = async () => { try { const id = idOf(action.row); const r = action.type === "submit" ? await citizenshipApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await citizenshipApi.auth({ id, narration: "approved" }) : action.type === "deauth" ? await citizenshipApi.deauth({ id, description: action.reason || "UNDEFINED" }) : action.type === "delete" ? await citizenshipApi.delete({ id, narration: "Citizenship no longer used" }) : await citizenshipApi.deleteAuth({ id }); notifications.success(apiMessage(r, "Citizenship action completed")); setAction(null); void load(); } catch (e) { notifications.error(e.message); } };
  const columns = [{ key: "name", label: "Citizenship", align: "left", render: (r) => r.name ?? "-" }, { key: "description", label: "Description", render: (r) => r.description ?? "-" }, { key: "status", label: "Status", render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: "Process Status", render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} variant="subtle" /> : "—") }, { key: "auth_status", label: "Authorization Status", render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} variant="subtle" /> : "—") }, { key: "actions", label: "Actions", sortable: false, render: (r) => { const buttons = getMakerCheckerButtons(r, { canAdd: can("Add"), canEdit: can("Edit"), canAuthorize: can("Authorize"), canDelete: can("Delete") }); const acts = [...(buttons.submitDraft ? [["submit", "Submit draft", Send, "submit"]] : []), ...(buttons.authorize ? [[buttons.isPendingDelete ? "deleteAuth" : "auth", "Authorize", ShieldCheck, buttons.isPendingDelete ? "deleteAuth" : "auth"]] : []), ...(buttons.deauthorize ? [["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(buttons.delete ? [["delete", "Delete", Trash2, "delete"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button className={actionButtonClass("view")} onClick={() => setView(r)}><Eye size={14} /></button></UiTooltip>{buttons.edit && <UiTooltip label="Edit"><button className={actionButtonClass("edit")} onClick={() => { setEditing(r); setForm({ name: r.name ?? "", description: r.description ?? "" }); setOpen(true); }}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button className={actionButtonClass("view")} onClick={() => setAudit(r)}><History size={14} /></button></UiTooltip>{acts.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button className={actionButtonClass(style)} onClick={() => setAction({ type, row: r, label, reason: "" })}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">Citizenship</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage citizenship master data.</p></div>{can("Add") && <button onClick={() => { setEditing(null); setForm(empty()); setOpen(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add citizenship</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search citizenship..." /><div className="mt-4"><DataTable columns={columns} rows={visible} rowKey={idOf} isLoading={loading} title="Citizenships" emptyTitle="No citizenships found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} /></div><CitizenshipForm open={open} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setOpen(false); setEditing(null); }} />{view && <Modal open title="View citizenship" onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Name", view.name], ["Description", view.description]].map(([l, v]) => <div key={l} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{l}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{v || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Citizenship #${idOf(audit)}`} fields={[["name", "Name"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => citizenshipApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} citizenship`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={() => setAction(null)} onConfirm={() => void run()}>{action.type === "deauth" && <textarea value={action.reason} onChange={(e) => setAction({ ...action, reason: e.target.value })} placeholder="Rejection reason" className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}
