import { useCallback, useEffect, useState } from "react";
import { institutionCurrencyApi } from "@/Services/Institutions/institutionCurrency.api";
import { useLiveChannel } from "@/Hooks/useLiveChannel";
import { API_ENDPOINTS } from "@/Utils/Constant";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";
import { masterApi } from "@/Services/Master/master.api";
export function useInstitutionCurrenciesQuery({ page = 1, limit = 10 } = {}) { const [state, setState] = useState({ data: [], pagination: {}, isLoading: true, error: null }); const refetch = useCallback(async () => { setState((s) => ({ ...s, isLoading: true, error: null })); try { const r = await institutionCurrencyApi.list({ page, limit }); setState({ data: Array.isArray(r?.data) ? r.data : [], pagination: r?.pagination ?? {}, isLoading: false, error: null }); } catch (error) { setState((s) => ({ ...s, isLoading: false, error })); } }, [page, limit]); useEffect(() => { void refetch(); }, [refetch]); useLiveChannel(API_ENDPOINTS.INSTITUTION.INSTITUTION_CURRENCY.LIST, () => void refetch()); return { ...state, refetch }; }
export function useInstitutionCurrencyMutation(method) { const [state, setState] = useState({ isPending: false, error: null }); const mutateAsync = useCallback(async (payload) => { setState({ isPending: true, error: null }); try { const result = await institutionCurrencyApi[method](payload); setState({ isPending: false, error: null }); notifications.success(apiMessage(result, "Institution currency action completed")); return result; } catch (error) { setState({ isPending: false, error }); notifications.error(error instanceof Error ? error.message : "Institution currency action failed"); throw error; } }, [method]); return { ...state, mutateAsync }; }
export function useMasterCurrencies() { const [state, setState] = useState({ currencies: [], loading: true, error: null }); useEffect(() => { let cancelled = false; masterApi.currencyList().then((currencies) => { if (!cancelled) setState({ currencies, loading: false, error: null }); }).catch((error) => { if (!cancelled) setState({ currencies: [], loading: false, error }); }); return () => { cancelled = true; }; }, []); return state; }
