import { useLiveChannel } from "@/Hooks/useLiveChannel";
import { API_ENDPOINTS } from "@/Utils/Constant";
import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Plus } from "lucide-react";
import { RowActions } from "@/Components/Common/RowActions";
import { useSelector } from "react-redux";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { Spinner } from "@/Components/Common/Spinner";
import { PendingChangesDiff, usePendingChanges } from "@/Components/Common/PendingChangesDiff";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { sourceOfFundApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";
import { matchesAction } from "@/Utils/Lib/actionAliases";
import { useConfigLabel } from "@/Utils/I18n/configFieldLabels";

const empty = () => ({ name: "", description: "", has_employer: false });
const idOf = (row) => row?.id ?? row?.source_of_fund_id;
const rowsOf = (response) => Array.isArray(response?.data) ? response.data : response?.data?.data ?? response?.data?.source_of_fund_array ?? [];
const allowed = (menus, action) => (menus ?? []).some((menu) => /source.?of.?fund/i.test(String(menu?.menu_name)) && (menu.actions ?? []).some((item) => matchesAction(item?.action_name ?? item?.name, action)));
function FundForm({ open, value, setValue, editing, saving, onClose, onSave }) { if (!open) return null; return <Modal open onClose={onClose} title={editing ? "Edit Source of Fund" : "Add Source of Fund"} footer={<><button type="button" onClick={onClose} disabled={saving} className="px-3 py-2 text-sm font-bold text-muted-foreground">Cancel</button><button type="submit" form="fund-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Save as draft</button><button type="submit" form="fund-form" data-mode="submit" disabled={saving} className="flex items-center justify-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">{saving && <Spinner size={13} />}{editing ? "Save changes" : "Add source"}</button></>}><form id="fund-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Source of fund<input required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-border p-3 outline-none focus:border-primary" /></label><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" checked={Boolean(value.has_employer)} onChange={(event) => setValue({ ...value, has_employer: event.target.checked })} /> Has employer</label></form></Modal>; }
export function SourceOfFund() {
  const tr = useConfigLabel();
  const menus = useSelector((state) => state.menu.menuArray); const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false), [actionPending, setActionPending] = useState(false);
  const can = (name) => allowed(menus, name); const load = useCallback(async () => { setLoading(true); try { const response = await sourceOfFundApi.list({ page, limit }); setRows(rowsOf(response)); setPagination(response?.pagination ?? response?.data?.pagination ?? {}); } catch (error) { notifications.error(error.message); } finally { setLoading(false); } }, [page, limit]); useEffect(() => { void load(); }, [load]);
  useLiveChannel(API_ENDPOINTS.MASTER_CONFIG.SOURCE_OF_FUND.LIST, () => void load());
  const pendingInfo = usePendingChanges(sourceOfFundApi.pending, action ? idOf(action.row) : null, Boolean(action) && ["auth", "deauth", "deleteAuth"].includes(action?.type));
  const visible = useMemo(() => rows.filter((row) => (tab === "all" || statusBucket(row) === tab) && `${row.name ?? ""} ${row.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (isDraft) => { if (!form.name.trim()) return notifications.error("Source of fund name is required"); setSaving(true); try { const payload = { ...form, has_employer: Boolean(form.has_employer), is_draft: isDraft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const response = await (editing ? sourceOfFundApi.edit(payload) : sourceOfFundApi.add(payload)); notifications.success(apiMessage(response, "Source of fund saved")); setOpen(false); setEditing(null); setForm(empty()); void load(); } catch (error) { notifications.error(error.message); } finally { setSaving(false); } };
  const run = async () => { setActionPending(true); try { const id = idOf(action.row); const response = action.type === "submit" ? await sourceOfFundApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await sourceOfFundApi.auth({ id, narration: action.reason || "" }) : action.type === "deauth" ? await sourceOfFundApi.deauth({ id, narration: action.reason || "UNDEFINED" }) : action.type === "delete" ? await sourceOfFundApi.delete({ id, narration: action.reason || "" }) : action.type === "deactivate" ? await sourceOfFundApi.deactivate({ id, narration: action.reason || "" }) : action.type === "reactivate" ? await sourceOfFundApi.reactivate({ id, narration: action.reason || "" }) : await sourceOfFundApi.deleteAuth({ id, narration: action.reason || "" }); notifications.success(apiMessage(response, "Source of fund action completed")); setAction(null); void load(); } catch (error) { notifications.error(error.message); } finally { setActionPending(false); } };
  const columns = [{ key: "name", label: tr("Source of fund"), render: (row) => row.name ?? "-" }, { key: "description", label: tr("Description"), render: (row) => row.description ?? "-" }, { key: "has_employer", label: tr("Has employer"), render: (row) => row.has_employer ? "Yes" : "No" }, { key: "status", label: tr("Status"), render: (row) => (row.status_name != null || row.status != null ? <StatusBadge status={String(row.status_name ?? (row.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: tr("Process Status"), render: (row) => (row.process_status_name ? <StatusBadge status={String(row.process_status_name)} /> : "—") }, { key: "auth_status", label: tr("Authorization Status"), render: (row) => (row.auth_status ? <StatusBadge status={String(row.auth_status)} /> : "—") }, { key: "actions", label: tr("Actions"), sortable: false, render: (row) => { const buttons = getMakerCheckerButtons(row, { canAdd: can("Add"), canEdit: can("Edit"), canAuthorize: can("Authorize"), canDelete: can("Delete") , canChangeStatus: can("Deactivate") || can("Reactivate")}); return <RowActions buttons={buttons} onView={() => setView(row)} onEdit={() => { setEditing(row); setForm({ name: row.name ?? "", description: row.description ?? "", has_employer: Boolean(row.has_employer) }); setOpen(true); }} onAudit={() => setAudit(row)} onSubmit={() => setAction({ type: "submit", row, label: "Submit", reason: "" })} onAuthorize={() => setAction({ type: buttons.isPendingDelete ? "deleteAuth" : "auth", row, label: "Authorize", reason: "" })} onDeauthorize={() => setAction({ type: "deauth", row, label: "Deauthorize", reason: "" })} onDeactivate={() => setAction({ type: "deactivate", row, label: "Deactivate", reason: "" })} onReactivate={() => setAction({ type: "reactivate", row, label: "Reactivate", reason: "" })} onDelete={() => setAction({ type: "delete", row, label: "Delete", reason: "" })} />; } }];
  return <div className="pt-1 pb-6"><div className="mb-3 flex items-start justify-between"><div><h1 className="text-xl font-black text-slate-800">{tr("Source of Fund")}</h1><p className="mt-1 text-xs font-medium text-muted-foreground">{tr("Manage source of fund master data.")}</p></div></div><div className="overflow-hidden rounded-2xl" style={{ background: "var(--glass-bg)", backdropFilter: "blur(16px)", border: "1px solid var(--glass-border)", boxShadow: "var(--glass-shadow)" }}><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder={tr("Search sources...")} actions={can("Add") && <button onClick={() => { setEditing(null); setForm(empty()); setOpen(true); }} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-bold text-white"><Plus size={14} /> {tr("Add")} {tr("source")}</button>} bare /><DataTable columns={columns} rows={visible} rowKey={idOf} isLoading={loading} title={tr("Sources of fund")} emptyTitle={tr("No sources of fund found")} serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} bare /></div><FundForm open={open} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setOpen(false); setEditing(null); }} />{view && <Modal open title={tr("View source of fund")} onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Name", view.name], ["Description", view.description], ["Has employer", view.has_employer ? "Yes" : "No"]].map(([label, value]) => <div key={label} className="rounded-xl border border-border p-3"><dt className="text-[10px] font-bold uppercase text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Source of Fund #${idOf(audit)}`} fields={[["name", "Name"], ["description", "Description"], ["has_employer", "Has employer"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => sourceOfFundApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} Source of Fund`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} pending={actionPending} onClose={() => setAction(null)} onConfirm={() => void run()}>{["auth", "deauth", "deleteAuth"].includes(action.type) && <PendingChangesDiff {...pendingInfo} />}<textarea value={action.reason ?? ""} onChange={(event) => setAction({ ...action, reason: event.target.value })} placeholder="Narration" className="mt-3 min-h-20 w-full rounded-xl border p-3" /></ConfirmDialog>}</div>;
}
