import { FilterSelect } from "@/Components/Common/FilterSelect";
import { blockNegativeKeyDown, blurOnWheel, clampNonNegative } from "@/Utils/Lib/numberInput";

// Field definitions + dropdown/input rendering for the Customer (indv_profile)
// wizard/resource — same [key, label, type, lookupKey?] tuple shape as
// digitalProductFields.jsx's CONFIGS. profile/contact/tax/employment are
// plain CONFIGS-driven sections; identification/address are handled by
// customerDynamicSteps.jsx instead (their form shape is driven one-row-per-
// type by wizard_config, not fixed). The remaining sections (business,
// financial_profile, source_of_fund, relationship, pep, kyc, screening,
// risk, document, communication, service_request) are real `sections` keys
// the backend already accepts but have no field-level form here yet — add a
// CONFIGS entry + a CUSTOMER_STEPS entry once their field lists are known,
// following this same pattern.
// inst_profile_id / party_type_id / ownership_id / onboarding_id are
// deliberately NOT fields here — a self-onboarding customer never picks
// any of these (see AddCustomerWizard.jsx's top comment): inst_profile_id
// comes from the logged-in session (useCustomerInstProfileId), party_type_id/
// ownership_id are resolved once from master data and hardcoded to
// CUSTOMER/INDIVIDUAL (useCustomerPartyOwnershipIds), and onboarding_id is
// generated by /customer/indv_onboarding/start on the Contact step and
// carried silently from then on. ownership_sub_type_id stays a real field
// here (still a genuine choice), but its options come from
// wizard_config.ownership_sub_types at render time, not a plain master list
// — see AddCustomerWizard.jsx's ownershipSubTypes lookup override — and the
// wizard skips rendering it entirely when the institution only has one.
export const CONFIGS = {
  profile: {
    title: "Personal Details",
    menuName: "Customer",
    fields: [
      ["ownership_sub_type_id", "Ownership sub type", "number", "ownershipSubTypes"],
      ["title", "Title", "text"],
      ["first_name", "First name", "text"],
      ["middle_name", "Middle name", "text"],
      ["last_name", "Last name", "text"],
      ["full_name", "Full name", "text"],
      ["preferred_name", "Preferred name", "text"],
      ["gender_id", "Gender", "number", "genders"],
      ["date_of_birth", "Date of birth", "date"],
      ["place_of_birth", "Place of birth", "text"],
      ["country_of_birth_id", "Country of birth", "number", "citizenships"],
      ["nationality_id", "Nationality", "number", "citizenships"],
      ["secondary_nationality_id", "Secondary nationality", "number", "citizenships"],
      ["marital_status_id", "Marital status", "number", "maritalStatuses"],
      ["father_name", "Father's name", "text"],
      ["mother_name", "Mother's name", "text"],
      ["spouse_name", "Spouse's name", "text"],
      ["disability_id", "Disability", "number", "disabilities"],
    ],
  },
  contact: {
    title: "Contact",
    fields: [
      ["primary_mobile", "Primary mobile", "text"],
      ["personal_email", "Personal email", "text"],
    ],
  },
  // tax / employment: plain CONFIGS-driven sections, same pattern as
  // profile/contact — unlike identification/address (whose rows are driven
  // one-per-type by wizard_config, see customerDynamicSteps.jsx), these are
  // a single object per profile with a fixed field list.
  tax: {
    title: "Tax Details",
    fields: [
      ["pan_number", "PAN number", "text"],
      ["pan_status", "PAN status", "text"],
      ["form60_reason", "Form 60 reason", "text"],
      ["tax_residency_country_id", "Tax residency country", "number", "citizenships"],
      ["tax_status_id", "Tax status", "number", "taxStatuses"],
      ["tax_classification_id", "Tax classification", "number", "taxClassifications"],
      ["fatca_status", "FATCA status", "text"],
      ["crs_status", "CRS status", "text"],
      ["tax_exemption_reason", "Tax exemption reason", "text"],
    ],
  },
  employment: {
    title: "Employment / Occupation",
    fields: [
      ["employment_id", "Employment status", "number", "employmentStatuses"],
      ["occupation_id", "Occupation", "number", "occupations"],
      ["designation_id", "Designation", "number", "designations"],
      ["employer_name", "Employer name", "text"],
      ["employer_address", "Employer address", "text"],
      ["employer_contact", "Employer contact", "text"],
    ],
  },
};

// Row-field templates for the two wizard_config-driven steps (one form
// section per applicable type, not one CONFIGS entry) — see
// customerDynamicSteps.jsx for how these are combined with each
// identification_types/address_types row from wizard_config.
export const IDENTIFICATION_ROW_FIELDS = [
  ["identification_number", "Identification number", "text"],
  ["date_of_issue", "Date of issue", "date"],
  ["date_of_expiry", "Date of expiry", "date"],
  ["issue_place", "Issue place", "text"],
];
export const ADDRESS_ROW_FIELDS = [
  ["address_line_1", "Address line 1", "text"],
  ["address_line_2", "Address line 2", "text"],
  ["city", "City", "text"],
  ["state", "State", "text"],
  ["country", "Country", "text"],
  ["postal_code", "Postal code", "text"],
];

// The dropdown-driven control (or plain input/date) for one field of one
// CONFIGS entry. `lookups` bundles every list the caller already fetches
// (institutions/partyTypes/ownershipTypes/genders/citizenships/disabilities);
// a caller only needs to pass the ones relevant to the fields it renders.
export function CustomerFieldInput({ fieldKey: key, type, value, onChange, lookups = {}, disabled = false }) {
  const {
    genders = [],
    citizenships = [],
    disabilities = [],
    maritalStatuses = [],
    ownershipSubTypes = [],
    taxStatuses = [],
    taxClassifications = [],
    employmentStatuses = [],
    occupations = [],
    designations = [],
  } = lookups;
  const LOOKUP_OPTIONS = {
    gender_id: { list: genders, placeholder: "Select gender" },
    country_of_birth_id: { list: citizenships, placeholder: "Select country of birth" },
    nationality_id: { list: citizenships, placeholder: "Select nationality" },
    secondary_nationality_id: { list: citizenships, placeholder: "Select secondary nationality" },
    tax_residency_country_id: { list: citizenships, placeholder: "Select tax residency country" },
    disability_id: { list: disabilities, placeholder: "Select disability" },
    marital_status_id: { list: maritalStatuses, placeholder: "Select marital status" },
    ownership_sub_type_id: { list: ownershipSubTypes, placeholder: "Select ownership sub type" },
    tax_status_id: { list: taxStatuses, placeholder: "Select tax status" },
    tax_classification_id: { list: taxClassifications, placeholder: "Select tax classification" },
    employment_id: { list: employmentStatuses, placeholder: "Select employment status", idKey: "employment_id" },
    occupation_id: { list: occupations, placeholder: "Select occupation" },
    designation_id: { list: designations, placeholder: "Select designation" },
  };
  const lookupConfig = LOOKUP_OPTIONS[key];
  if (lookupConfig) {
    return (
      <FilterSelect
        className="mt-1.5"
        value={value ?? ""}
        onChange={onChange}
        disabled={disabled}
        options={[
          { value: "", label: lookupConfig.placeholder },
          ...lookupConfig.list.map((item) => {
            const id = lookupConfig.idKey ? item[lookupConfig.idKey] : item.id;
            return { value: id, label: item.name ?? item.code ?? String(id) };
          }),
        ]}
      />
    );
  }
  return (
    <input
      type={type === "number" ? "number" : type === "date" ? "date" : "text"}
      min={type === "number" ? 0 : undefined}
      value={value ?? ""}
      onKeyDown={type === "number" ? blockNegativeKeyDown : undefined}
      onWheel={type === "number" ? blurOnWheel : undefined}
      onChange={(e) => onChange(type === "number" ? clampNonNegative(e.target.value) : e.target.value)}
      disabled={disabled}
      className="mt-1.5 w-full rounded-xl border px-3 py-2.5 disabled:bg-slate-50 disabled:text-slate-500"
    />
  );
}
