import { useNavigate } from "react-router-dom";
import { FilterSelect } from "@/Components/Common/FilterSelect";
import { blockNegativeKeyDown, blurOnWheel, clampNonNegative } from "@/Utils/Lib/numberInput";

// Field definitions + dropdown/input rendering for the Customer (indv_profile)
// wizard/resource — same [key, label, type, lookupKey?] tuple shape as
// digitalProductFields.jsx's CONFIGS. profile/contact/tax/employment are
// plain CONFIGS-driven sections; identification/address are handled by
// customerDynamicSteps.jsx instead (their form shape is driven one-row-per-
// type by wizard_config, not fixed). The remaining sections (business,
// financial_profile, source_of_fund, relationship, pep, kyc, screening,
// risk, document, communication, service_request) are real `sections` keys
// the backend already accepts but have no field-level form here yet — add a
// CONFIGS entry + a CUSTOMER_STEPS entry once their field lists are known,
// following this same pattern.
// inst_profile_id / party_type_id / ownership_id / onboarding_id are
// deliberately NOT fields here — a self-onboarding customer never picks
// any of these (see AddCustomerWizard.jsx's top comment): inst_profile_id
// comes from the logged-in session (useCustomerInstProfileId), party_type_id/
// ownership_id are resolved once from master data and hardcoded to
// CUSTOMER/INDIVIDUAL (useCustomerPartyOwnershipIds), and onboarding_id is
// generated by /customer/indv_onboarding/start on the Contact step and
// carried silently from then on. ownership_sub_type_id stays a real field
// here (still a genuine choice), but its options come from
// wizard_config.ownership_sub_types at render time, not a plain master list
// — see AddCustomerWizard.jsx's ownershipSubTypes lookup override — and the
// wizard skips rendering it entirely when the institution only has one.
export const CONFIGS = {
  profile: {
    title: "Personal Details",
    menuName: "Customer",
    fields: [
      ["ownership_sub_type_id", "Ownership sub type", "number", "ownershipSubTypes"],
      ["title", "Title", "text"],
      ["first_name", "First name", "text"],
      ["middle_name", "Middle name", "text"],
      ["last_name", "Last name", "text"],
      ["full_name", "Full name", "text"],
      ["preferred_name", "Preferred name", "text"],
      ["gender_id", "Gender", "number", "genders"],
      ["date_of_birth", "Date of birth", "date"],
      ["place_of_birth", "Place of birth", "text"],
      ["country_of_birth_id", "Country of birth", "number", "citizenships"],
      ["nationality_id", "Nationality", "number", "citizenships"],
      ["secondary_nationality_id", "Secondary nationality", "number", "citizenships"],
      ["marital_status_id", "Marital status", "number", "maritalStatuses"],
      ["father_name", "Father's name", "text"],
      ["mother_name", "Mother's name", "text"],
      ["spouse_name", "Spouse's name", "text"],
      ["disability_id", "Disability", "number", "disabilities"],
    ],
  },
  contact: {
    title: "Contact",
    fields: [
      ["primary_mobile", "Primary mobile", "text"],
      ["personal_email", "Personal email", "text"],
    ],
  },
  // tax / employment: plain CONFIGS-driven sections, same pattern as
  // profile/contact — unlike identification/address (whose rows are driven
  // one-per-type by wizard_config, see customerDynamicSteps.jsx), these are
  // a single object per profile with a fixed field list.
  // Field names/types here match the backend's confirmed `tax` section
  // contract exactly (verified against a real submit rejection listing
  // "unknown field(s)" for the old names) — see the PR description for the
  // full before/after table. `pan_status_id`/`tax_exemption_status_id` both
  // come from the same `indv_tax_status` master; `fatca_classification_id`/
  // `crs_classification_id` both come from `indv_tax_classification`.
  tax: {
    title: "Tax Details",
    fields: [
      ["pan", "PAN", "text"],
      ["pan_status_id", "PAN status", "number", "taxStatuses"],
      ["form_60_applicable", "Form 60 applicable", "boolean"],
      ["form_60_reference", "Form 60 reference", "text"],
      ["tax_residency_country_id", "Tax residency country", "number", "countries"],
      ["foreign_tax_identification_number", "Foreign tax identification number", "text"],
      ["fatca_applicable", "FATCA applicable", "boolean"],
      ["crs_applicable", "CRS applicable", "boolean"],
      ["fatca_classification_id", "FATCA classification", "number", "taxClassifications"],
      ["crs_classification_id", "CRS classification", "number", "taxClassifications"],
      ["tax_exemption_status_id", "Tax exemption status", "number", "taxStatuses"],
      ["tax_exemption_number", "Tax exemption number", "text"],
      ["tax_exemption_expiry_date", "Tax exemption expiry date", "date"],
    ],
  },
  employment: {
    title: "Employment / Occupation",
    fields: [
      ["employment_id", "Employment status", "number", "employmentStatuses"],
      ["occupation_id", "Occupation", "number", "occupations"],
      ["designation_id", "Designation", "number", "designations"],
      ["employer_name", "Employer name", "text"],
      ["employer_address", "Employer address", "text"],
      ["employer_phone", "Employer phone", "text"],
      ["employer_email", "Employer email", "text"],
    ],
  },
  // Business Details — only relevant when the Employment step's chosen
  // status is self-employed/business/professional-ish; gated at the step
  // level (isBusinessEmployment in customerWizardConfig.js), not per-field
  // here, since it's an all-or-nothing section.
  business: {
    title: "Business Details",
    fields: [
      ["business_name", "Business name", "text"],
      ["business_type", "Business type / nature", "text"],
      ["registration_number", "Registration number", "text"],
      ["business_address", "Business address", "text"],
      ["annual_turnover_id", "Annual turnover", "number", "turnovers"],
      ["years_in_business", "Years in business", "number"],
      ["tax_registration_number", "GST / tax registration number", "text"],
    ],
  },
  financial_profile: {
    title: "Financial Profile",
    fields: [
      ["annual_income", "Annual income", "number"],
      ["net_worth", "Net worth", "number"],
      ["expected_transaction_volume", "Expected transaction volume", "number"],
      ["expected_transaction_count", "Expected transaction count", "number"],
      ["purpose_of_account_id", "Purpose of account", "number", "accountPurposes"],
      ["purpose_of_relationship", "Purpose of relationship (if not listed)", "text"],
    ],
  },
  source_of_fund: {
    title: "Source of Funds",
    fields: [["source_of_fund_id", "Source of funds", "number", "sourceOfFunds"]],
  },
  // PEP Details — pep_status_id/pep_category_id/position/organization/
  // country/start_date/end_date only make sense once is_pep is checked;
  // gated per-field via CustomerStepFields' fieldFilter (see
  // AddCustomerWizard.jsx/EditCustomerWizard.jsx/ViewCustomerWizard.jsx).
  pep: {
    title: "PEP Details",
    fields: [
      ["is_pep", "Are you a politically exposed person?", "boolean"],
      ["pep_status_id", "PEP status", "number", "pepStatuses"],
      ["pep_category_id", "PEP category", "number", "pepCategories"],
      ["position", "Position", "text"],
      ["organization", "Organization", "text"],
      ["country_id", "Country", "number", "countries"],
      ["start_date", "Start date", "date"],
      ["end_date", "End date", "date"],
    ],
  },
  // The backend contract for `communication` is an ARRAY of rows (one per
  // channel preference), not a single object — see
  // customerWizardShared.jsx's buildSectionEditPayload/pickFields special
  // case for how a single-row form here gets wrapped/unwrapped on the wire.
  // `preferred_channel` is the channel's own code (e.g. "EMAIL"), not an id.
  communication: {
    title: "Communication",
    fields: [
      ["preferred_channel", "Preferred channel (e.g. EMAIL, SMS, WHATSAPP)", "text"],
      ["preferred_language_id", "Preferred language", "number", "languages"],
      ["marketing_opt_in", "Marketing opt-in", "boolean"],
      ["notification_opt_in", "Notification opt-in", "boolean"],
    ],
  },
};

// Row-field templates for the two wizard_config-driven steps (one form
// section per applicable type, not one CONFIGS entry) — see
// customerDynamicSteps.jsx for how these are combined with each
// identification_types/address_types row from wizard_config.
export const IDENTIFICATION_ROW_FIELDS = [
  ["identification_number", "Identification number", "text"],
  ["date_of_issue", "Date of issue", "date"],
  ["date_of_expiry", "Date of expiry", "date"],
  ["issue_place", "Issue place", "text"],
];
// No `state` field exists on the backend's `address` section — use
// province_id/district_id instead — and `country` must be `country_id` (an
// id from /master/country), never a free-text name.
export const ADDRESS_ROW_FIELDS = [
  ["address_line_1", "Address line 1", "text"],
  ["address_line_2", "Address line 2", "text"],
  ["city", "City", "text"],
  ["district_id", "District", "number", "districts"],
  ["province_id", "Province", "number", "provinces"],
  ["country_id", "Country", "number", "countries"],
  ["postal_code", "Postal code", "text"],
];

// Relationships step — freely-addable rows (not one-per-wizard_config-row
// like identification/address), see customerDynamicSteps.jsx's
// RelationshipStepFields. Guardian sub-block only appears when the row's
// relationship_type_id resolves to "GUARDIAN" AND the customer is a minor.
export const RELATIONSHIP_ROW_FIELDS = [
  ["relationship_type_id", "Relationship type", "number", "relationshipTypes"],
  ["name", "Name", "text"],
  ["contact_number", "Contact number", "text"],
  ["share_percentage", "Share / percentage (if nominee)", "number"],
];
export const GUARDIAN_ROW_FIELDS = [
  ["guardian_name", "Guardian name", "text"],
  ["guardian_relationship", "Guardian relationship to minor", "text"],
  ["guardian_contact_number", "Guardian contact number", "text"],
  ["guardian_id_number", "Guardian ID number", "text"],
];

// The dropdown-driven control (or plain input/date) for one field of one
// CONFIGS entry. `lookups` bundles every list the caller already fetches
// (institutions/partyTypes/ownershipTypes/genders/citizenships/disabilities);
// a caller only needs to pass the ones relevant to the fields it renders.
// Master page (route slug + label) behind each lookup dropdown, for the
// "Add ..." row at the end of its list. Lookups with no master screen (country,
// language) are left out and get no add row.
const MASTER_ADD_TARGETS = {
  gender_id: ["/gender", "gender"],
  country_of_birth_id: ["/citizenship", "citizenship"],
  nationality_id: ["/citizenship", "citizenship"],
  secondary_nationality_id: ["/citizenship", "citizenship"],
  disability_id: ["/disability", "disability"],
  marital_status_id: ["/maritalstatus", "marital status"],
  ownership_sub_type_id: ["/ownershipsubtype", "ownership sub type"],
  employment_id: ["/employment", "employment status"],
  occupation_id: ["/occupation", "occupation"],
  designation_id: ["/designation", "designation"],
  annual_turnover_id: ["/turnover", "turnover"],
  source_of_fund_id: ["/sourceoffund", "source of funds"],
  pep_status_id: ["/pepstatus", "PEP status"],
  pep_category_id: ["/pepcategory", "PEP category"],
  relationship_type_id: ["/relationshiptype", "relationship type"],
  pan_status_id: ["/taxstatus", "tax status"],
  tax_exemption_status_id: ["/taxstatus", "tax status"],
  fatca_classification_id: ["/taxclassification", "tax classification"],
  crs_classification_id: ["/taxclassification", "tax classification"],
  purpose_of_account_id: ["/accountpurpose", "account purpose"],
  province_id: ["/province", "province"],
  district_id: ["/district", "district"],
};

export function CustomerFieldInput({ fieldKey: key, type, value, onChange, lookups = {}, disabled = false }) {
  const navigate = useNavigate();
  const {
    genders = [],
    citizenships = [],
    disabilities = [],
    maritalStatuses = [],
    ownershipSubTypes = [],
    taxStatuses = [],
    taxClassifications = [],
    employmentStatuses = [],
    occupations = [],
    designations = [],
    turnovers = [],
    sourceOfFunds = [],
    pepStatuses = [],
    pepCategories = [],
    relationshipTypes = [],
    languages = [],
    countries = [],
    provinces = [],
    districts = [],
    accountPurposes = [],
  } = lookups;
  const LOOKUP_OPTIONS = {
    gender_id: { list: genders, placeholder: "Select gender" },
    country_of_birth_id: { list: citizenships, placeholder: "Select country of birth" },
    nationality_id: { list: citizenships, placeholder: "Select nationality" },
    secondary_nationality_id: { list: citizenships, placeholder: "Select secondary nationality" },
    disability_id: { list: disabilities, placeholder: "Select disability" },
    marital_status_id: { list: maritalStatuses, placeholder: "Select marital status" },
    ownership_sub_type_id: { list: ownershipSubTypes, placeholder: "Select ownership sub type" },
    employment_id: { list: employmentStatuses, placeholder: "Select employment status", idKey: "employment_id" },
    occupation_id: { list: occupations, placeholder: "Select occupation" },
    designation_id: { list: designations, placeholder: "Select designation" },
    annual_turnover_id: { list: turnovers, placeholder: "Select annual turnover" },
    source_of_fund_id: { list: sourceOfFunds, placeholder: "Select source of funds" },
    pep_status_id: { list: pepStatuses, placeholder: "Select PEP status" },
    pep_category_id: { list: pepCategories, placeholder: "Select PEP category" },
    relationship_type_id: { list: relationshipTypes, placeholder: "Select relationship type" },
    preferred_language_id: { list: languages, placeholder: "Select preferred language" },
    tax_residency_country_id: { list: countries, placeholder: "Select tax residency country" },
    pan_status_id: { list: taxStatuses, placeholder: "Select PAN status" },
    tax_exemption_status_id: { list: taxStatuses, placeholder: "Select tax exemption status" },
    fatca_classification_id: { list: taxClassifications, placeholder: "Select FATCA classification" },
    crs_classification_id: { list: taxClassifications, placeholder: "Select CRS classification" },
    purpose_of_account_id: { list: accountPurposes, placeholder: "Select purpose of account" },
    country_id: { list: countries, placeholder: "Select country" },
    province_id: { list: provinces, placeholder: "Select province" },
    district_id: { list: districts, placeholder: "Select district" },
  };
  const lookupConfig = LOOKUP_OPTIONS[key];
  if (lookupConfig) {
    return (
      <FilterSelect
        className="mt-1.5"
        value={value ?? ""}
        onChange={onChange}
        disabled={disabled}
        addAction={MASTER_ADD_TARGETS[key] ? { label: `Add ${MASTER_ADD_TARGETS[key][1]}`, onClick: () => navigate(MASTER_ADD_TARGETS[key][0]) } : undefined}
        options={[
          { value: "", label: lookupConfig.placeholder },
          ...lookupConfig.list.map((item) => {
            const id = lookupConfig.idKey ? item[lookupConfig.idKey] : item.id;
            return { value: id, label: item.name ?? item.code ?? String(id) };
          }),
        ]}
      />
    );
  }
  // type === "boolean" never actually reaches here — CustomerStepFields
  // (customerWizardShared.jsx) renders a CheckboxPill directly for it
  // instead, same as DigitalProductStepFields does. Kept as a fallback for
  // any future direct caller of CustomerFieldInput with a boolean field.
  if (type === "boolean") {
    return (
      <input
        type="checkbox"
        checked={Boolean(value)}
        onChange={(e) => onChange(e.target.checked)}
        disabled={disabled}
        className="mt-1.5 h-4 w-4 rounded border-slate-300"
      />
    );
  }
  return (
    <input
      type={type === "number" ? "number" : type === "date" ? "date" : "text"}
      min={type === "number" ? 0 : undefined}
      value={value ?? ""}
      onKeyDown={type === "number" ? blockNegativeKeyDown : undefined}
      onWheel={type === "number" ? blurOnWheel : undefined}
      onChange={(e) => onChange(type === "number" ? clampNonNegative(e.target.value) : e.target.value)}
      disabled={disabled}
      className="mt-1.5 w-full rounded-xl border px-3 py-2.5 disabled:bg-slate-50 disabled:text-slate-500"
    />
  );
}
