import { deriveStatusFlags } from "@/Components/MakerChecker/statusFlags";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { useSelector } from "react-redux";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { genderApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const empty = () => ({ name: "", description: "" });
const idOf = (row) => row?.id ?? row?.gender_id;
const rowsOf = (response) => Array.isArray(response?.data) ? response.data : response?.data?.data ?? response?.data?.gender_array ?? [];
const isDraft = (row) => deriveStatusFlags(row).draft;
const isPending = (row) => deriveStatusFlags(row).pending;
const isPendingDelete = (row) => deriveStatusFlags(row).pendingDelete;
const canAction = (menus, action) => (menus ?? []).some((menu) => /gender/i.test(String(menu?.menu_name)) && (menu.actions ?? []).some((item) => { const name = String(item?.action_name ?? item?.name ?? "").toLowerCase(); return name === action.toLowerCase() || action === "Add" && name === "create" || action === "Authorize" && name === "authorise"; }));

function GenderForm({ open, value, setValue, editing, saving, onClose, onSave }) {
  if (!open) return null;
  return <Modal open onClose={onClose} title={editing ? "Edit Gender" : "Add Gender"} footer={<><button type="button" onClick={onClose} disabled={saving} className="px-3 py-2 text-sm font-bold text-slate-500">Cancel</button><button type="submit" form="gender-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Save as draft</button><button type="submit" form="gender-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">{editing ? "Save changes" : "Add Gender"}</button></>}><form id="gender-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Gender name<input required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label></form></Modal>;
}

export function Gender() {
  const menus = useSelector((state) => state.menu.menuArray); const [page, setPage] = useState(1); const [limit, setLimit] = useState(10); const [rows, setRows] = useState([]); const [pagination, setPagination] = useState({}); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [tab, setTab] = useState("all"); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [view, setView] = useState(null); const [audit, setAudit] = useState(null); const [action, setAction] = useState(null); const [saving, setSaving] = useState(false);
  const can = (name) => canAction(menus, name); const load = useCallback(async () => { setLoading(true); try { const response = await genderApi.list({ page, limit }); setRows(rowsOf(response)); setPagination(response?.pagination ?? response?.data?.pagination ?? {}); } catch (error) { notifications.error(error.message); } finally { setLoading(false); } }, [page, limit]); useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rows.filter((row) => (tab === "all" || statusBucket(row) === tab) && `${row.name ?? ""} ${row.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (draftMode) => { if (!form.name.trim()) return notifications.error("Gender name is required"); setSaving(true); try { const payload = { ...form, is_draft: draftMode, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const response = await (editing ? genderApi.edit(payload) : genderApi.add(payload)); notifications.success(apiMessage(response, "Gender saved")); setOpen(false); setEditing(null); setForm(empty()); void load(); } catch (error) { notifications.error(error.message); } finally { setSaving(false); } };
  const run = async () => { try { const id = idOf(action.row); const response = action.type === "submit" ? await genderApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await genderApi.auth({ id }) : action.type === "deauth" ? await genderApi.deauth({ id, description: action.reason || "UNDEFINED" }) : action.type === "delete" ? await genderApi.delete({ id }) : await genderApi.deleteAuth({ id }); notifications.success(apiMessage(response, "Gender action completed")); setAction(null); void load(); } catch (error) { notifications.error(error.message); } };
  const columns = [{ key: "name", label: "Gender", render: (row) => row.name ?? "-" }, { key: "description", label: "Description", render: (row) => row.description ?? "-" }, { key: "status", label: "Status", render: (row) => (row.status_name != null || row.status != null ? <StatusBadge status={String(row.status_name ?? (row.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: "Process Status", render: (row) => (row.process_status_name ? <StatusBadge status={String(row.process_status_name)} /> : "—") }, { key: "auth_status", label: "Authorization Status", render: (row) => (row.auth_status ? <StatusBadge status={String(row.auth_status)} /> : "—") }, { key: "actions", label: "Actions", sortable: false, render: (row) => { const draft = isDraft(row), pending = isPending(row), pendingDelete = isPendingDelete(row); const actions = [...((can("Submit") || can("Add")) && draft ? [["submit", "Submit draft", Send, "submit"]] : []), ...(can("Authorize") && pending && !pendingDelete ? [["auth", "Authorize", ShieldCheck, "auth"], ["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(can("Delete") ? [["delete", "Delete", Trash2, "delete"]] : []), ...(can("Authorize") && pendingDelete ? [["deleteAuth", "Authorize delete", ShieldCheck, "deleteAuth"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button className={actionButtonClass("view")} onClick={() => setView(row)}><Eye size={14} /></button></UiTooltip>{can("Edit") && <UiTooltip label="Edit"><button className={actionButtonClass("edit")} onClick={() => { setEditing(row); setForm({ name: row.name ?? "", description: row.description ?? "" }); setOpen(true); }}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button className={actionButtonClass("view")} onClick={() => setAudit(row)}><History size={14} /></button></UiTooltip>{actions.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button className={actionButtonClass(style)} onClick={() => setAction({ type, row, label, reason: "" })}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">Gender</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage gender master data.</p></div>{can("Add") && <button onClick={() => { setEditing(null); setForm(empty()); setOpen(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add Gender</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search genders..." /><div className="mt-4"><DataTable columns={columns} rows={visible} rowKey={idOf} isLoading={loading} title="Genders" emptyTitle="No genders found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} /></div><GenderForm open={open} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setOpen(false); setEditing(null); }} />{view && <Modal open title="View gender" onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Name", view.name], ["Description", view.description]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Gender #${idOf(audit)}`} fields={[["name", "Name"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => genderApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} Gender`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={() => setAction(null)} onConfirm={() => void run()}>{action.type === "deauth" && <textarea value={action.reason} onChange={(event) => setAction({ ...action, reason: event.target.value })} placeholder="Rejection reason" className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}
