import { deriveStatusFlags } from "@/Components/MakerChecker/statusFlags";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { useSelector } from "react-redux";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { occupationApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const empty = () => ({ name: "", description: "" });
const rowsOf = (r) => Array.isArray(r?.data) ? r.data : r?.data?.data ?? r?.data?.Occupation_array ?? [];
const idOf = (r) => r?.id ?? r?.Occupation_id;
const draft = (r) => deriveStatusFlags(r).draft;
const pending = (r) => deriveStatusFlags(r).pending;
const pendingDelete = (r) => deriveStatusFlags(r).pendingDelete;
const allowed = (menus, action) => (menus ?? []).some((m) => /Occupation/i.test(String(m?.menu_name)) && (m.actions ?? []).some((a) => { const n = String(a?.action_name ?? a?.name ?? "").toLowerCase(); return n === action.toLowerCase() || action === "Add" && n === "create" || action === "Authorize" && n === "authorise"; }));
function OccupationForm({ open, value, setValue, editing, saving, onClose, onSave }) { return <Modal open={open} onClose={onClose} title={editing ? "Edit Occupation" : "Add Occupation"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-slate-500">Cancel</button><button type="submit" form="Occupation-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Save as draft</button><button type="submit" form="Occupation-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">{saving ? "Saving..." : editing ? "Save changes" : "Add Occupation"}</button></>}><form id="Occupation-form" onSubmit={(e) => { e.preventDefault(); onSave(e.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Occupation name<input required value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label></form></Modal>; }
export function Occupation() {
  const menus = useSelector((s) => s.menu.menuArray); const [page, setPage] = useState(1), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false);
  const can = (a) => allowed(menus, a); const load = useCallback(async () => { setLoading(true); try { const r = await occupationApi.list({ page, limit: 10 }); setRows(rowsOf(r)); setPagination(r?.pagination ?? r?.data?.pagination ?? {}); } catch (e) { notifications.error(e.message); } finally { setLoading(false); } }, [page]); useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rows.filter((r) => (tab === "all" || statusBucket(r) === tab) && `${r.name ?? ""} ${r.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (isDraft) => { if (!form.name.trim()) return notifications.error("Occupation name is required"); setSaving(true); try { const p = { ...form, is_draft: isDraft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const r = await (editing ? occupationApi.edit(p) : occupationApi.add(p)); notifications.success(apiMessage(r, "Occupation saved")); setOpen(false); setEditing(null); setForm(empty()); void load(); } catch (e) { notifications.error(e.message); } finally { setSaving(false); } };
  const run = async () => { try { const id = idOf(action.row); const r = action.type === "submit" ? await occupationApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await occupationApi.auth({ id, narration: "approved" }) : action.type === "deauth" ? await occupationApi.deauth({ id, description: action.reason || "UNDEFINED" }) : action.type === "delete" ? await occupationApi.delete({ id, narration: "Occupation no longer used" }) : await occupationApi.deleteAuth({ id }); notifications.success(apiMessage(r, "Occupation action completed")); setAction(null); void load(); } catch (e) { notifications.error(e.message); } };
  const columns = [{ key: "name", label: "Occupation", align: "left", render: (r) => r.name ?? "-" }, { key: "description", label: "Description", render: (r) => r.description ?? "-" }, { key: "status", label: "Status", render: (r) => <StatusBadge status={String(r.status_name ?? r.auth_status ?? r.status ?? "")} /> }, { key: "actions", label: "Actions", sortable: false, render: (r) => { const d = draft(r), p = pending(r), pd = pendingDelete(r); const acts = [...((can("Submit") || can("Add")) && d ? [["submit", "Submit draft", Send, "submit"]] : []), ...(can("Authorize") && p && !pd ? [["auth", "Authorize", ShieldCheck, "auth"], ["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(can("Delete") ? [["delete", "Delete", Trash2, "delete"]] : []), ...(can("Authorize") && pd ? [["deleteAuth", "Authorize delete", ShieldCheck, "deleteAuth"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button className={actionButtonClass("view")} onClick={() => setView(r)}><Eye size={14} /></button></UiTooltip>{can("Edit") && <UiTooltip label="Edit"><button className={actionButtonClass("edit")} onClick={() => { setEditing(r); setForm({ name: r.name ?? "", description: r.description ?? "" }); setOpen(true); }}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button className={actionButtonClass("view")} onClick={() => setAudit(r)}><History size={14} /></button></UiTooltip>{acts.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button className={actionButtonClass(style)} onClick={() => setAction({ type, row: r, label, reason: "" })}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">Occupation</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage Occupation master data.</p></div>{can("Add") && <button onClick={() => { setEditing(null); setForm(empty()); setOpen(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add Occupation</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search Occupation..." /><div className="mt-4"><DataTable columns={columns} rows={visible} rowKey={idOf} isLoading={loading} title="Occupations" emptyTitle="No Occupations found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage }} /></div><OccupationForm open={open} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setOpen(false); setEditing(null); }} />{view && <Modal open title="View Occupation" onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Name", view.name], ["Description", view.description]].map(([l, v]) => <div key={l} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{l}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{v || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Occupation #${idOf(audit)}`} fields={[["name", "Name"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => occupationApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} Occupation`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={() => setAction(null)} onConfirm={() => void run()}>{action.type === "deauth" && <textarea value={action.reason} onChange={(e) => setAction({ ...action, reason: e.target.value })} placeholder="Rejection reason" className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}



