import { deriveStatusFlags } from "@/Components/MakerChecker/statusFlags";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { useSelector } from "react-redux";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { sourceOfFundApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const empty = () => ({ name: "", description: "", has_employer: false });
const idOf = (row) => row?.id ?? row?.source_of_fund_id;
const rowsOf = (response) => Array.isArray(response?.data) ? response.data : response?.data?.data ?? response?.data?.source_of_fund_array ?? [];
const draft = (row) => deriveStatusFlags(row).draft;
const pending = (row) => deriveStatusFlags(row).pending;
const pendingDelete = (row) => deriveStatusFlags(row).pendingDelete;
const allowed = (menus, action) => (menus ?? []).some((menu) => /source.?of.?fund/i.test(String(menu?.menu_name)) && (menu.actions ?? []).some((item) => { const name = String(item?.action_name ?? item?.name ?? "").toLowerCase(); return name === action.toLowerCase() || action === "Add" && name === "create" || action === "Authorize" && name === "authorise"; }));
function FundForm({ open, value, setValue, editing, saving, onClose, onSave }) { if (!open) return null; return <Modal open onClose={onClose} title={editing ? "Edit Source of Fund" : "Add Source of Fund"} footer={<><button type="button" onClick={onClose} disabled={saving} className="px-3 py-2 text-sm font-bold text-slate-500">Cancel</button><button type="submit" form="fund-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Save as draft</button><button type="submit" form="fund-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">{editing ? "Save changes" : "Add source"}</button></>}><form id="fund-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Source of fund<input required value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(event) => setValue({ ...value, description: event.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" checked={Boolean(value.has_employer)} onChange={(event) => setValue({ ...value, has_employer: event.target.checked })} /> Has employer</label></form></Modal>; }
export function SourceOfFund() {
  const menus = useSelector((state) => state.menu.menuArray); const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false);
  const can = (name) => allowed(menus, name); const load = useCallback(async () => { setLoading(true); try { const response = await sourceOfFundApi.list({ page, limit }); setRows(rowsOf(response)); setPagination(response?.pagination ?? response?.data?.pagination ?? {}); } catch (error) { notifications.error(error.message); } finally { setLoading(false); } }, [page, limit]); useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rows.filter((row) => (tab === "all" || statusBucket(row) === tab) && `${row.name ?? ""} ${row.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (isDraft) => { if (!form.name.trim()) return notifications.error("Source of fund name is required"); setSaving(true); try { const payload = { ...form, has_employer: Boolean(form.has_employer), is_draft: isDraft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const response = await (editing ? sourceOfFundApi.edit(payload) : sourceOfFundApi.add(payload)); notifications.success(apiMessage(response, "Source of fund saved")); setOpen(false); setEditing(null); setForm(empty()); void load(); } catch (error) { notifications.error(error.message); } finally { setSaving(false); } };
  const run = async () => { try { const id = idOf(action.row); const response = action.type === "submit" ? await sourceOfFundApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await sourceOfFundApi.auth({ id }) : action.type === "deauth" ? await sourceOfFundApi.deauth({ id, description: action.reason || "UNDEFINED" }) : action.type === "delete" ? await sourceOfFundApi.delete({ id }) : await sourceOfFundApi.deleteAuth({ id }); notifications.success(apiMessage(response, "Source of fund action completed")); setAction(null); void load(); } catch (error) { notifications.error(error.message); } };
  const columns = [{ key: "name", label: "Source of fund", render: (row) => row.name ?? "-" }, { key: "description", label: "Description", render: (row) => row.description ?? "-" }, { key: "has_employer", label: "Has employer", render: (row) => row.has_employer ? "Yes" : "No" }, { key: "status", label: "Status", render: (row) => (row.status_name != null || row.status != null ? <StatusBadge status={String(row.status_name ?? (row.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: "Process Status", render: (row) => (row.process_status_name ? <StatusBadge status={String(row.process_status_name)} /> : "—") }, { key: "auth_status", label: "Authorization Status", render: (row) => (row.auth_status ? <StatusBadge status={String(row.auth_status)} /> : "—") }, { key: "actions", label: "Actions", sortable: false, render: (row) => { const d = draft(row), p = pending(row), pd = pendingDelete(row); const acts = [...((can("Submit") || can("Add")) && d ? [["submit", "Submit draft", Send, "submit"]] : []), ...(can("Authorize") && p && !pd ? [["auth", "Authorize", ShieldCheck, "auth"], ["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(can("Delete") ? [["delete", "Delete", Trash2, "delete"]] : []), ...(can("Authorize") && pd ? [["deleteAuth", "Authorize delete", ShieldCheck, "deleteAuth"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button className={actionButtonClass("view")} onClick={() => setView(row)}><Eye size={14} /></button></UiTooltip>{can("Edit") && <UiTooltip label="Edit"><button className={actionButtonClass("edit")} onClick={() => { setEditing(row); setForm({ name: row.name ?? "", description: row.description ?? "", has_employer: Boolean(row.has_employer) }); setOpen(true); }}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button className={actionButtonClass("view")} onClick={() => setAudit(row)}><History size={14} /></button></UiTooltip>{acts.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button className={actionButtonClass(style)} onClick={() => setAction({ type, row, label, reason: "" })}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">Source of Fund</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage source of fund master data.</p></div>{can("Add") && <button onClick={() => { setEditing(null); setForm(empty()); setOpen(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add source</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search sources..." /><div className="mt-4"><DataTable columns={columns} rows={visible} rowKey={idOf} isLoading={loading} title="Sources of fund" emptyTitle="No sources of fund found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} /></div><FundForm open={open} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setOpen(false); setEditing(null); }} />{view && <Modal open title="View source of fund" onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Name", view.name], ["Description", view.description], ["Has employer", view.has_employer ? "Yes" : "No"]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Source of Fund #${idOf(audit)}`} fields={[["name", "Name"], ["description", "Description"], ["has_employer", "Has employer"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => sourceOfFundApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} Source of Fund`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={() => setAction(null)} onConfirm={() => void run()}>{action.type === "deauth" && <textarea value={action.reason} onChange={(event) => setAction({ ...action, reason: event.target.value })} placeholder="Rejection reason" className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}
