import { useLiveChannel } from "@/Hooks/useLiveChannel";
import { API_ENDPOINTS } from "@/Utils/Constant";
import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { matchesAction } from "@/Utils/Lib/actionAliases";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSelector } from "react-redux";
import { Plus } from "lucide-react";
import { RowActions } from "@/Components/Common/RowActions";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { Spinner } from "@/Components/Common/Spinner";
import { PendingChangesDiff, usePendingChanges } from "@/Components/Common/PendingChangesDiff";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { FilterSelect } from "@/Components/Common/FilterSelect";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { districtApi, villageApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";
import { useConfigLabel } from "@/Utils/I18n/configFieldLabels";

const empty = () => ({ district_id: "", name: "", description: "" });
const rowsOf = (r) => Array.isArray(r?.data) ? r.data : r?.data?.data ?? r?.data?.village_array ?? [];
const idOf = (r) => r?.id ?? r?.village_id;
function usePermission(action) { const menus = useSelector((s) => s.menu.menuArray); return useMemo(() => (menus ?? []).some((m) => /village/i.test(String(m?.menu_name)) && (m.actions ?? []).some((item) => matchesAction(item?.action_name ?? item?.name, action))), [menus, action]); }
function VillageForm({ open, value, setValue, districts, editing, saving, onClose, onSave }) { const tr = useConfigLabel(); return <Modal open={open} onClose={onClose} title={editing ? "Edit village" : "Add village"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-muted-foreground disabled:opacity-50">Cancel</button><button type="submit" form="village-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600 disabled:opacity-50">Save as draft</button><button type="submit" form="village-form" data-mode="submit" disabled={saving} className="flex items-center justify-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving && <Spinner size={13} />}{saving ? "Saving..." : editing ? "Save changes" : "Add village"}</button></>}><form id="village-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">District<FilterSelect className="mt-1.5" value={value.district_id} onChange={(next) => setValue({ ...value, district_id: next })} options={[{ value: "", label: tr("Select district") }, ...districts.map((d) => ({ value: idOf(d), label: d.name ?? d.district_name ?? `District #${idOf(d)}` }))]} /></label><label className="text-sm font-semibold text-slate-700">Village name<input required value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-border p-3 outline-none focus:border-primary" /></label></form></Modal>; }
export function Village() {
  const tr = useConfigLabel();
  const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [districts, setDistricts] = useState([]), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [formOpen, setFormOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false), [actionPending, setActionPending] = useState(false);
  const canAdd = usePermission("Add"), canEdit = usePermission("Edit"), canDelete = usePermission("Delete"), canAuthorize = usePermission("Authorize"), canSubmit = usePermission("Submit"), canDeactivate = usePermission("Deactivate"), canReactivate = usePermission("Reactivate");
  const load = useCallback(async () => { setLoading(true); try { const r = await villageApi.list({ page, limit }); setRows(rowsOf(r)); setPagination(r?.pagination ?? r?.data?.pagination ?? {}); } catch (e) { notifications.error(e.message); } finally { setLoading(false); } }, [page, limit]);
  useEffect(() => { void load(); }, [load]);
  useLiveChannel(API_ENDPOINTS.MASTER_CONFIG.VILLAGE.LIST, () => void load());
  const pendingInfo = usePendingChanges(villageApi.pending, action ? idOf(action.row) : null, Boolean(action) && ["auth", "deauth", "deleteAuth"].includes(action?.type)); useEffect(() => { districtApi.getActive().then((r) => setDistricts(rowsOf(r))).catch((e) => notifications.error(e.message)); }, []);
  const filtered = useMemo(() => rows.filter((r) => (tab === "all" || statusBucket(r) === tab) && `${r.name ?? ""} ${r.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (draft) => { const districtId = Number(form.district_id); if (!form.name.trim() || !Number.isInteger(districtId) || districtId <= 0) return notifications.error("District and village name are required"); setSaving(true); try { const payload = { ...form, district_id: districtId, is_draft: draft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const r = await (editing ? villageApi.edit(payload) : villageApi.add(payload)); if (editing && (editing.auth_status === "DRAFT" || editing.process_status_name === "Draft") && !draft) { await villageApi.submit({ id: idOf(editing), narration: "Submitted for review" }); } notifications.success(apiMessage(r, "Village saved")); setFormOpen(false); setEditing(null); setForm(empty()); void load(); } catch (e) { notifications.error(e.message); } finally { setSaving(false); } };
  const execute = async () => { setActionPending(true); try { const id = idOf(action.row); const r = action.type === "submit" ? await villageApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await villageApi.auth({ id, narration: action.reason || "" }) : action.type === "deauth" ? await villageApi.deauth({ id, narration: action.reason || "UNDEFINED" }) : action.type === "delete" ? await villageApi.delete({ id, narration: action.reason || "" }) : action.type === "deactivate" ? await villageApi.deactivate({ id, narration: action.reason || "" }) : action.type === "reactivate" ? await villageApi.reactivate({ id, narration: action.reason || "" }) : await villageApi.deleteAuth({ id, narration: action.reason || "" }); notifications.success(apiMessage(r, "Village action completed")); setAction(null); void load(); } catch (e) { notifications.error(e.message); } finally { setActionPending(false); } };
  const columns = [{ key: "name", label: tr("Village"), align: "left", render: (r) => r.name ?? "-" }, { key: "district", label: tr("District"), render: (r) => districts.find((d) => String(idOf(d)) === String(r.district_id))?.name ?? r.district_name ?? r.district_id }, { key: "description", label: tr("Description"), render: (r) => r.description ?? "-" }, { key: "status", label: tr("Status"), render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: tr("Process Status"), render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} /> : "—") }, { key: "auth_status", label: tr("Authorization Status"), render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} /> : "—") }, { key: "actions", label: tr("Actions"), sortable: false, render: (r) => { const visibility = getMakerCheckerButtons(r, { canAdd, canEdit, canAuthorize, canDelete, canSubmit, canChangeStatus: canDeactivate || canReactivate }); return <RowActions buttons={visibility} onView={() => setView(r)} onEdit={() => { setEditing(r); setForm({ district_id: String(r.district_id ?? ""), name: r.name ?? "", description: r.description ?? "" }); setFormOpen(true); }} onAudit={() => setAudit(r)} onSubmit={() => setAction({ type: "submit", row: r, label: "Submit", reason: "" })} onAuthorize={() => setAction({ type: visibility.isPendingDelete ? "deleteAuth" : "auth", row: r, label: "Authorize", reason: "" })} onDeauthorize={() => setAction({ type: "deauth", row: r, label: "Deauthorize", reason: "" })} onDeactivate={() => setAction({ type: "deactivate", row: r, label: "Deactivate", reason: "" })} onReactivate={() => setAction({ type: "reactivate", row: r, label: "Reactivate", reason: "" })} onDelete={() => setAction({ type: "delete", row: r, label: "Delete", reason: "" })} />; } }];
  return <div className="pt-1 pb-6"><div className="mb-3 flex items-start justify-between gap-3"><div><h1 className="text-xl font-black text-slate-800">{tr("Village")}</h1><p className="mt-1 text-xs font-medium text-muted-foreground">{tr("Manage villages under active districts.")}</p></div></div><div className="overflow-hidden rounded-2xl" style={{ background: "var(--glass-bg)", backdropFilter: "blur(16px)", border: "1px solid var(--glass-border)", boxShadow: "var(--glass-shadow)" }}><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder={tr("Search villages...")} actions={canAdd && <button onClick={() => { setEditing(null); setForm(empty()); setFormOpen(true); }} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-bold text-white"><Plus size={14} /> {tr("Add")} {tr("village")}</button>} bare /><DataTable columns={columns} rows={filtered} rowKey={idOf} isLoading={loading} title={tr("Villages")} emptyTitle={tr("No villages found")} serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} bare /></div><VillageForm open={formOpen} value={form} setValue={setForm} districts={districts} editing={editing} saving={saving} onSave={save} onClose={() => { setFormOpen(false); setEditing(null); }} />{view && <Modal open title={tr("View village")} onClose={() => setView(null)} size="sm"><dl className="grid gap-3 sm:grid-cols-2">{[["Village", view.name], ["District", districts.find((d) => String(idOf(d)) === String(view.district_id))?.name ?? view.district_id], ["Description", view.description]].map(([label, value]) => <div key={label} className="rounded-xl border border-border p-3"><dt className="text-[10px] font-bold uppercase text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Village #${idOf(audit)}`} fields={[["name", "Village"], ["district_id", "District ID"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => villageApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} village`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} pending={actionPending} onClose={() => setAction(null)} onConfirm={() => void execute()}>{["auth", "deauth", "deleteAuth"].includes(action.type) && <PendingChangesDiff {...pendingInfo} />}<textarea value={action.description ?? action.reason ?? ""} onChange={(e) => setAction({ ...action, description: e.target.value, reason: e.target.value })} placeholder="Narration" className="mt-3 min-h-20 w-full rounded-xl border p-3" /></ConfirmDialog>}</div>;
}
