import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSelector } from "react-redux";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { districtApi, villageApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const empty = () => ({ district_id: "", name: "", description: "" });
const rowsOf = (r) => Array.isArray(r?.data) ? r.data : r?.data?.data ?? r?.data?.village_array ?? [];
const idOf = (r) => r?.id ?? r?.village_id;
function usePermission(action) { const menus = useSelector((s) => s.menu.menuArray); return useMemo(() => (menus ?? []).some((m) => /village/i.test(String(m?.menu_name)) && (m.actions ?? []).some((a) => { const name = String(a?.action_name ?? a?.name ?? "").toLowerCase(); return name === action.toLowerCase() || (action === "Add" && name === "create") || (action === "Authorize" && name === "authorise"); })), [menus, action]); }
function VillageForm({ open, value, setValue, districts, editing, saving, onClose, onSave }) { return <Modal open={open} onClose={onClose} title={editing ? "Edit village" : "Add village"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-slate-500 disabled:opacity-50">Cancel</button><button type="submit" form="village-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600 disabled:opacity-50">Save as draft</button><button type="submit" form="village-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : editing ? "Save changes" : "Add village"}</button></>}><form id="village-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">District<select required value={value.district_id} onChange={(e) => setValue({ ...value, district_id: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none focus:border-primary"><option value="">Select district</option>{districts.map((d) => <option key={idOf(d)} value={idOf(d)}>{d.name ?? d.district_name ?? `District #${idOf(d)}`}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Village name<input required value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label></form></Modal>; }
export function Village() {
  const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [districts, setDistricts] = useState([]), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [formOpen, setFormOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false);
  const canAdd = usePermission("Add"), canEdit = usePermission("Edit"), canDelete = usePermission("Delete"), canAuthorize = usePermission("Authorize"), canSubmit = usePermission("Submit");
  const load = useCallback(async () => { setLoading(true); try { const r = await villageApi.list({ page, limit }); setRows(rowsOf(r)); setPagination(r?.pagination ?? r?.data?.pagination ?? {}); } catch (e) { notifications.error(e.message); } finally { setLoading(false); } }, [page, limit]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { districtApi.getActive().then((r) => setDistricts(rowsOf(r))).catch((e) => notifications.error(e.message)); }, []);
  const filtered = useMemo(() => rows.filter((r) => (tab === "all" || statusBucket(r) === tab) && `${r.name ?? ""} ${r.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (draft) => { const districtId = Number(form.district_id); if (!form.name.trim() || !Number.isInteger(districtId) || districtId <= 0) return notifications.error("District and village name are required"); setSaving(true); try { const payload = { ...form, district_id: districtId, is_draft: draft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const r = await (editing ? villageApi.edit(payload) : villageApi.add(payload)); notifications.success(apiMessage(r, "Village saved")); setFormOpen(false); setEditing(null); setForm(empty()); void load(); } catch (e) { notifications.error(e.message); } finally { setSaving(false); } };
  const execute = async () => { try { const id = idOf(action.row); const r = action.type === "submit" ? await villageApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await villageApi.auth({ id }) : action.type === "deauth" ? await villageApi.deauth({ id, description: action.description || "UNDEFINED" }) : action.type === "delete" ? await villageApi.delete({ id }) : await villageApi.deleteAuth({ id }); notifications.success(apiMessage(r, "Village action completed")); setAction(null); void load(); } catch (e) { notifications.error(e.message); } };
  const columns = [{ key: "name", label: "Village", align: "left", render: (r) => r.name ?? "-" }, { key: "district", label: "District", render: (r) => districts.find((d) => String(idOf(d)) === String(r.district_id))?.name ?? r.district_name ?? r.district_id }, { key: "description", label: "Description", render: (r) => r.description ?? "-" }, { key: "status", label: "Status", render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: "Process Status", render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} variant="subtle" /> : "—") }, { key: "auth_status", label: "Authorization Status", render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} variant="subtle" /> : "—") }, { key: "actions", label: "Actions", sortable: false, render: (r) => { const visibility = getMakerCheckerButtons(r, { canAdd, canEdit, canAuthorize, canDelete, canSubmit }); const actions = [...(visibility.submitDraft ? [["submit", "Submit draft", Send, "submit"]] : []), ...(visibility.authorize ? [[visibility.isPendingDelete ? "deleteAuth" : "auth", "Authorize", ShieldCheck, visibility.isPendingDelete ? "deleteAuth" : "auth"]] : []), ...(visibility.deauthorize ? [["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(visibility.delete ? [["delete", "Delete", Trash2, "delete"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button onClick={() => setView(r)} className={actionButtonClass("view")}><Eye size={14} /></button></UiTooltip>{visibility.edit && <UiTooltip label="Edit"><button onClick={() => { setEditing(r); setForm({ district_id: String(r.district_id ?? ""), name: r.name ?? "", description: r.description ?? "" }); setFormOpen(true); }} className={actionButtonClass("edit")}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button onClick={() => setAudit(r)} className={actionButtonClass("view")}><History size={14} /></button></UiTooltip>{actions.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button onClick={() => setAction({ type, row: r, label, description: "" })} className={actionButtonClass(style)}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">Village</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage villages under active districts.</p></div>{canAdd && <button onClick={() => { setEditing(null); setForm(empty()); setFormOpen(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add village</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search villages..." /><div className="mt-4"><DataTable columns={columns} rows={filtered} rowKey={idOf} isLoading={loading} title="Villages" emptyTitle="No villages found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} /></div><VillageForm open={formOpen} value={form} setValue={setForm} districts={districts} editing={editing} saving={saving} onSave={save} onClose={() => { setFormOpen(false); setEditing(null); }} />{view && <Modal open title="View village" onClose={() => setView(null)} size="sm"><dl className="grid gap-3 sm:grid-cols-2">{[["Village", view.name], ["District", districts.find((d) => String(idOf(d)) === String(view.district_id))?.name ?? view.district_id], ["Description", view.description]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Village #${idOf(audit)}`} fields={[["name", "Village"], ["district_id", "District ID"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => villageApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} village`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={() => setAction(null)} onConfirm={() => void execute()}>{action.type === "deauth" && <textarea value={action.description} onChange={(e) => setAction({ ...action, description: e.target.value })} placeholder="Rejection reason" className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}
