export const ROUTES = {
  root: "/",
  login: "/login",
  setup: "/setup",
  dashboard: "/dashboard",
  pending: "/pending",
  institutions: "/institutions",
  institutionCreate: "/institutions/create",
  institutionDetail: (id = ":id") => "/institutions/" + id,
  users: "/users",
  profiles: "/profiles",
  applications: "/applications",
  menus: "/menus",
  kyc: "/kyc",
};
