import { useLiveChannel } from "@/Hooks/useLiveChannel";
import { reconcileSetter } from "@/Utils/Lib/liveReconcile";
import { API_ENDPOINTS } from "@/Utils/Constant";
import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSelector } from "react-redux";
import { Plus } from "lucide-react";
import { RowActions } from "@/Components/Common/RowActions";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { Spinner } from "@/Components/Common/Spinner";
import { PendingChangesDiff, usePendingChanges } from "@/Components/Common/PendingChangesDiff";
import { DataTable } from "@/Components/Common/DataTable";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { Modal } from "@/Components/Common/Modal";
import { FilterSelect } from "@/Components/Common/FilterSelect";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { districtApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";
import { matchesAction } from "@/Utils/Lib/actionAliases";
import { useConfigLabel } from "@/Utils/I18n/configFieldLabels";

const EMPTY = { province_id: "", name: "", description: "" };
const rowsOf = (response) => Array.isArray(response?.data) ? response.data : response?.data?.data ?? response?.data?.district_array ?? [];
const idOf = (row) => row?.id ?? row?.district_id;

function useDistrictPermission(action) {
  const menus = useSelector((state) => state.menu.menuArray);
  return useMemo(() => (menus ?? []).some((menu) => /district/i.test(String(menu?.menu_name)) &&
    (menu.actions ?? []).some((item) => matchesAction(item?.action_name ?? item?.name, action))), [menus, action]);
}

function DistrictForm({ open, form, setForm, provinces, editing, saving, onClose, onSave }) {
  const tr = useConfigLabel();
  return <Modal open={open} onClose={onClose} title={editing ? "Edit district" : "Add district"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-slate-500 disabled:opacity-50">Cancel</button><button type="submit" form="district-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600 disabled:opacity-50">Save as draft</button><button type="submit" form="district-form" data-mode="submit" disabled={saving} className="flex items-center justify-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving && <Spinner size={13} />}{saving ? "Saving..." : editing ? "Save changes" : "Add district"}</button></>}>
    <form id="district-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4">
      <label className="text-sm font-semibold text-slate-700">Province<FilterSelect className="mt-1.5" value={form.province_id} onChange={(next) => setForm({ ...form, province_id: next })} options={[{ value: "", label: tr("Select province") }, ...provinces.map((p) => ({ value: idOf(p), label: p.name ?? p.province_name ?? `Province #${idOf(p)}` }))]} /></label>
      <label className="text-sm font-semibold text-slate-700">District name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label>
      <label className="text-sm font-semibold text-slate-700">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label>
    </form>
  </Modal>;
}

export function District() {
  const tr = useConfigLabel();
  const [page, setPage] = useState(1); const [limit, setLimit] = useState(10); const [rows, setRows] = useState([]); const [pagination, setPagination] = useState({}); const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""); const [tab, setTab] = useState("all"); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [view, setView] = useState(null); const [action, setAction] = useState(null); const [audit, setAudit] = useState(null); const [provinces, setProvinces] = useState([]); const [saving, setSaving] = useState(false); const [actionPending, setActionPending] = useState(false);
  const canAdd = useDistrictPermission("Add"); const canEdit = useDistrictPermission("Edit"); const canDelete = useDistrictPermission("Delete"); const canAuthorize = useDistrictPermission("Authorize"); const canSubmit = useDistrictPermission("Submit"); const canDeactivate = useDistrictPermission("Deactivate"); const canReactivate = useDistrictPermission("Reactivate");
  const load = useCallback(async () => { setLoading(true); try { const result = await districtApi.list({ page, limit }); setRows(rowsOf(result)); setPagination(result?.pagination ?? result?.data?.pagination ?? {}); } catch (error) { notifications.error(error.message); } finally { setLoading(false); } }, [page, limit]);
  useEffect(() => { void load(); }, [load]);
  useLiveChannel(API_ENDPOINTS.MASTER_CONFIG.DISTRICT.LIST, reconcileSetter(setRows, { insertNew: false }));
  const pendingInfo = usePendingChanges(districtApi.pending, action ? idOf(action.row) : null, Boolean(action) && ["auth", "deauth", "deleteAuth"].includes(action?.type));
  useEffect(() => { districtApi.activeProvinces().then((result) => setProvinces(rowsOf(result))).catch((error) => notifications.error(error.message)); }, []);
  const visible = useMemo(() => rows.filter((row) => (tab === "all" || statusBucket(row) === tab) && `${row.name ?? ""} ${row.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, search, tab]);
  const close = () => { setAction(null); };
  const save = async (draft) => { const provinceId = Number(form.province_id); if (!form.name.trim() || !Number.isInteger(provinceId) || provinceId <= 0) return notifications.error("Province and district name are required"); setSaving(true); try { const payload = { ...form, province_id: provinceId, is_draft: draft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const result = await (editing ? districtApi.edit(payload) : districtApi.add(payload)); notifications.success(apiMessage(result, "District saved")); setShowForm(false); setEditing(null); setForm(EMPTY); void load(); } catch (error) { notifications.error(error.message); } finally { setSaving(false); } };
  const run = async () => { if (!action) return; setActionPending(true); try { const id = idOf(action.row); const result = action.type === "submit" ? await districtApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await districtApi.auth({ id, narration: action.remark || "" }) : action.type === "deauth" ? await districtApi.deauth({ id, narration: action.remark || "UNDEFINED" }) : action.type === "delete" ? await districtApi.delete({ id, narration: action.remark || "" }) : action.type === "deactivate" ? await districtApi.deactivate({ id, narration: action.remark || "" }) : action.type === "reactivate" ? await districtApi.reactivate({ id, narration: action.remark || "" }) : await districtApi.deleteAuth({ id, narration: action.remark || "" }); notifications.success(apiMessage(result, "District action completed")); close(); void load(); } catch (error) { notifications.error(error.message); } finally { setActionPending(false); } };
  const columns = [{ key: "name", label: tr("District"), align: "left", render: (r) => r.name ?? "-" }, { key: "province_id", label: tr("Province"), render: (r) => provinces.find((p) => String(idOf(p)) === String(r.province_id))?.name ?? r.province_name ?? r.province_id }, { key: "description", label: tr("Description"), render: (r) => r.description ?? "-" }, { key: "status", label: tr("Status"), render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: tr("Process Status"), render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} /> : "—") }, { key: "auth_status", label: tr("Authorization Status"), render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} /> : "—") }, { key: "actions", label: tr("Actions"), sortable: false, render: (r) => { const visibility = getMakerCheckerButtons(r, { canAdd, canEdit, canAuthorize, canDelete, canSubmit, canChangeStatus: canDeactivate || canReactivate }); return <RowActions buttons={visibility} onView={() => setView(r)} onEdit={() => { setEditing(r); setForm({ province_id: String(r.province_id ?? ""), name: r.name ?? "", description: r.description ?? "" }); setShowForm(true); }} onAudit={() => setAudit(r)} onSubmit={() => setAction({ type: "submit", row: r, label: "Submit", remark: "" })} onAuthorize={() => setAction({ type: visibility.isPendingDelete ? "deleteAuth" : "auth", row: r, label: "Authorize", remark: "" })} onDeauthorize={() => setAction({ type: "deauth", row: r, label: "Deauthorize", remark: "" })} onDeactivate={() => setAction({ type: "deactivate", row: r, label: "Deactivate", remark: "" })} onReactivate={() => setAction({ type: "reactivate", row: r, label: "Reactivate", remark: "" })} onDelete={() => setAction({ type: "delete", row: r, label: "Delete", remark: "" })} />; } }];
  return <div className="pt-1 pb-6"><div className="mb-3 flex items-start justify-between gap-3"><div><h1 className="text-xl font-black text-slate-800">{tr("District")}</h1><p className="mt-1 text-xs font-medium text-slate-500">{tr("Manage districts under active provinces.")}</p></div></div><div className="overflow-hidden rounded-2xl" style={{ background: "var(--glass-bg)", backdropFilter: "blur(16px)", border: "1px solid var(--glass-border)", boxShadow: "var(--glass-shadow)" }}><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder={tr("Search districts...")} actions={canAdd && <button onClick={() => { setEditing(null); setForm(EMPTY); setShowForm(true); }} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-bold text-white"><Plus size={14} /> {tr("Add")} {tr("district")}</button>} bare /><DataTable columns={columns} rows={visible} isLoading={loading} rowKey={idOf} title={tr("Districts")} emptyTitle={tr("No districts found")} serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} bare /></div><DistrictForm open={showForm} form={form} setForm={setForm} provinces={provinces} editing={editing} saving={saving} onSave={save} onClose={() => { setShowForm(false); setEditing(null); }} />{view && <Modal open title={tr("View district")} onClose={() => setView(null)} size="sm"><dl className="grid gap-3 sm:grid-cols-2">{[["District", view.name], ["Province", provinces.find((p) => String(idOf(p)) === String(view.province_id))?.name ?? view.province_id], ["Description", view.description]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `District #${idOf(audit)}`} fields={[["name", "District"], ["province_id", "Province ID"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(auditPage, limit) => districtApi.audit({ id: idOf(audit), page: auditPage, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} district`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} pending={actionPending} onClose={close} onConfirm={() => void run()}>{["auth", "deauth", "deleteAuth"].includes(action.type) && <PendingChangesDiff {...pendingInfo} />}<textarea placeholder="Narration" value={action.remark ?? ""} onChange={(e) => setAction({ ...action, remark: e.target.value })} className="mt-3 min-h-20 w-full rounded-xl border p-3" /></ConfirmDialog>}</div>;
}
