import { deriveStatusFlags } from "@/Components/MakerChecker/statusFlags";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSelector } from "react-redux";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { provinceApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const empty = () => ({ name: "", description: "" });
const rowsOf = (r) => Array.isArray(r?.data) ? r.data : r?.data?.data ?? r?.data?.province_array ?? [];
const idOf = (r) => r?.id ?? r?.province_id;
const draft = (r) => deriveStatusFlags(r).draft;
const pending = (r) => deriveStatusFlags(r).pending;
const pendingDelete = (r) => deriveStatusFlags(r).pendingDelete;

function usePermission(action) { const menus = useSelector((s) => s.menu.menuArray); return useMemo(() => (menus ?? []).some((m) => /province/i.test(String(m?.menu_name)) && (m.actions ?? []).some((a) => { const name = String(a?.action_name ?? a?.name ?? "").toLowerCase(); return name === action.toLowerCase() || (action === "Add" && name === "create") || (action === "Authorize" && name === "authorise"); })), [menus, action]); }

function ProvinceForm({ open, value, setValue, editing, saving, onClose, onSave }) { return <Modal open={open} onClose={onClose} title={editing ? "Edit province" : "Add province"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-slate-500 disabled:opacity-50">Cancel</button><button type="submit" form="province-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600 disabled:opacity-50">Save as draft</button><button type="submit" form="province-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : editing ? "Save changes" : "Add province"}</button></>}><form id="province-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Province name<input required value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label></form></Modal>; }

export function Province() {
  const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [formOpen, setFormOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false);
  const canAdd = usePermission("Add"), canEdit = usePermission("Edit"), canDelete = usePermission("Delete"), canAuthorize = usePermission("Authorize"), canSubmit = usePermission("Submit");
  const load = useCallback(async () => { setLoading(true); try { const r = await provinceApi.list({ page, limit }); setRows(rowsOf(r)); setPagination(r?.pagination ?? r?.data?.pagination ?? {}); } catch (e) { notifications.error(e.message); } finally { setLoading(false); } }, [page, limit]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => rows.filter((r) => (tab === "all" || statusBucket(r) === tab) && `${r.name ?? ""} ${r.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (isDraft) => { if (!form.name.trim()) return notifications.error("Province name is required"); setSaving(true); try { const payload = { ...form, is_draft: isDraft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const r = await (editing ? provinceApi.edit(payload) : provinceApi.add(payload)); notifications.success(apiMessage(r, "Province saved")); setFormOpen(false); setEditing(null); setForm(empty()); void load(); } catch (e) { notifications.error(e.message); } finally { setSaving(false); } };
  const execute = async () => { try { const id = idOf(action.row); const r = action.type === "submit" ? await provinceApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await provinceApi.auth({ id }) : action.type === "deauth" ? await provinceApi.deauth({ id, description: action.description || "UNDEFINED" }) : action.type === "delete" ? await provinceApi.delete({ id }) : await provinceApi.deleteAuth({ id }); notifications.success(apiMessage(r, "Province action completed")); setAction(null); void load(); } catch (e) { notifications.error(e.message); } };
  const columns = [{ key: "name", label: "Province", align: "left", render: (r) => r.name ?? "-" }, { key: "description", label: "Description", render: (r) => r.description ?? "-" }, { key: "status", label: "Status", render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: "Process Status", render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} /> : "—") }, { key: "auth_status", label: "Authorization Status", render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} /> : "—") }, { key: "actions", label: "Actions", sortable: false, render: (r) => { const actions = [...((canSubmit || canAdd) && draft(r) ? [["submit", "Submit draft", Send, "submit"]] : []), ...(canAuthorize && pending(r) && !pendingDelete(r) ? [["auth", "Authorize", ShieldCheck, "auth"], ["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(canDelete ? [["delete", "Delete", Trash2, "delete"]] : []), ...(canAuthorize && pendingDelete(r) ? [["deleteAuth", "Authorize delete", ShieldCheck, "deleteAuth"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button onClick={() => setView(r)} className={actionButtonClass("view")}><Eye size={14} /></button></UiTooltip>{canEdit && <UiTooltip label="Edit"><button onClick={() => { setEditing(r); setForm({ name: r.name ?? "", description: r.description ?? "" }); setFormOpen(true); }} className={actionButtonClass("edit")}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button onClick={() => setAudit(r)} className={actionButtonClass("view")}><History size={14} /></button></UiTooltip>{actions.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button onClick={() => setAction({ type, row: r, label, description: "" })} className={actionButtonClass(style)}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">Province</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage provinces.</p></div>{canAdd && <button onClick={() => { setEditing(null); setForm(empty()); setFormOpen(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add province</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search provinces..." /><div className="mt-4"><DataTable columns={columns} rows={filtered} rowKey={idOf} isLoading={loading} title="Provinces" emptyTitle="No provinces found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} /></div><ProvinceForm open={formOpen} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setFormOpen(false); setEditing(null); }} />{view && <Modal open title="View province" onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Province", view.name], ["Description", view.description]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Province #${idOf(audit)}`} fields={[["name", "Province"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => provinceApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} province`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={() => setAction(null)} onConfirm={() => void execute()}>{action.type === "deauth" && <textarea value={action.description} onChange={(e) => setAction({ ...action, description: e.target.value })} placeholder="Rejection reason" className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}
