import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSelector } from "react-redux";
import { Eye, History, Pencil, Plus, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { DataTable } from "@/Components/Common/DataTable";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { UiTooltip } from "@/Components/Common/UiTooltip";
import { Modal } from "@/Components/Common/Modal";
import { actionButtonClass } from "@/Components/Common/actionStyles";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { districtApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";

const EMPTY = { province_id: "", name: "", description: "" };
const rowsOf = (response) => Array.isArray(response?.data) ? response.data : response?.data?.data ?? response?.data?.district_array ?? [];
const idOf = (row) => row?.id ?? row?.district_id;

function useDistrictPermission(action) {
  const menus = useSelector((state) => state.menu.menuArray);
  return useMemo(() => (menus ?? []).some((menu) => /district/i.test(String(menu?.menu_name)) && (menu.actions ?? []).some((item) => {
    const name = String(item?.action_name ?? item?.name ?? "").toLowerCase();
    return name === action.toLowerCase() || (action === "Add" && name === "create") || (action === "Authorize" && name === "authorise");
  })), [menus, action]);
}

function DistrictForm({ open, form, setForm, provinces, editing, saving, onClose, onSave }) {
  return <Modal open={open} onClose={onClose} title={editing ? "Edit district" : "Add district"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-slate-500 disabled:opacity-50">Cancel</button><button type="submit" form="district-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600 disabled:opacity-50">Save as draft</button><button type="submit" form="district-form" data-mode="submit" disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving..." : editing ? "Save changes" : "Add district"}</button></>}>
    <form id="district-form" onSubmit={(event) => { event.preventDefault(); onSave(event.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4">
      <label className="text-sm font-semibold text-slate-700">Province<select required value={form.province_id} onChange={(e) => setForm({ ...form, province_id: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none focus:border-primary"><option value="">Select province</option>{provinces.map((p) => <option key={idOf(p)} value={idOf(p)}>{p.name ?? p.province_name ?? `Province #${idOf(p)}`}</option>)}</select></label>
      <label className="text-sm font-semibold text-slate-700">District name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-primary" /></label>
      <label className="text-sm font-semibold text-slate-700">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-primary" /></label>
    </form>
  </Modal>;
}

export function District() {
  const [page, setPage] = useState(1); const [limit, setLimit] = useState(10); const [rows, setRows] = useState([]); const [pagination, setPagination] = useState({}); const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""); const [tab, setTab] = useState("all"); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [view, setView] = useState(null); const [action, setAction] = useState(null); const [audit, setAudit] = useState(null); const [provinces, setProvinces] = useState([]); const [saving, setSaving] = useState(false);
  const canAdd = useDistrictPermission("Add"); const canEdit = useDistrictPermission("Edit"); const canDelete = useDistrictPermission("Delete"); const canAuthorize = useDistrictPermission("Authorize"); const canSubmit = useDistrictPermission("Submit");
  const load = useCallback(async () => { setLoading(true); try { const result = await districtApi.list({ page, limit }); setRows(rowsOf(result)); setPagination(result?.pagination ?? result?.data?.pagination ?? {}); } catch (error) { notifications.error(error.message); } finally { setLoading(false); } }, [page, limit]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { districtApi.activeProvinces().then((result) => setProvinces(rowsOf(result))).catch((error) => notifications.error(error.message)); }, []);
  const visible = useMemo(() => rows.filter((row) => (tab === "all" || statusBucket(row) === tab) && `${row.name ?? ""} ${row.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, search, tab]);
  const close = () => { setAction(null); };
  const save = async (draft) => { const provinceId = Number(form.province_id); if (!form.name.trim() || !Number.isInteger(provinceId) || provinceId <= 0) return notifications.error("Province and district name are required"); setSaving(true); try { const payload = { ...form, province_id: provinceId, is_draft: draft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const result = await (editing ? districtApi.edit(payload) : districtApi.add(payload)); notifications.success(apiMessage(result, "District saved")); setShowForm(false); setEditing(null); setForm(EMPTY); void load(); } catch (error) { notifications.error(error.message); } finally { setSaving(false); } };
  const run = async () => { if (!action) return; try { const id = idOf(action.row); const result = action.type === "submit" ? await districtApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await districtApi.auth({ id }) : action.type === "deauth" ? await districtApi.deauth({ id, description: action.remark || "UNDEFINED" }) : action.type === "delete" ? await districtApi.delete({ id }) : await districtApi.deleteAuth({ id }); notifications.success(apiMessage(result, "District action completed")); close(); void load(); } catch (error) { notifications.error(error.message); } };
  const columns = [{ key: "name", label: "District", align: "left", render: (r) => r.name ?? "-" }, { key: "province_id", label: "Province", render: (r) => provinces.find((p) => String(idOf(p)) === String(r.province_id))?.name ?? r.province_name ?? r.province_id }, { key: "description", label: "Description", render: (r) => r.description ?? "-" }, { key: "status", label: "Status", render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: "Process Status", render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} variant="subtle" /> : "—") }, { key: "auth_status", label: "Authorization Status", render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} variant="subtle" /> : "—") }, { key: "actions", label: "Actions", sortable: false, render: (r) => { const visibility = getMakerCheckerButtons(r, { canAdd, canEdit, canAuthorize, canDelete, canSubmit }); const buttons = [...(visibility.submitDraft ? [["submit", "Submit draft", Send, "submit"]] : []), ...(visibility.authorize ? [[visibility.isPendingDelete ? "deleteAuth" : "auth", "Authorize", ShieldCheck, visibility.isPendingDelete ? "deleteAuth" : "auth"]] : []), ...(visibility.deauthorize ? [["deauth", "Deauthorize", ShieldOff, "deauth"]] : []), ...(visibility.delete ? [["delete", "Delete", Trash2, "delete"]] : [])]; return <div className="flex justify-center gap-1"><UiTooltip label="View"><button className={actionButtonClass("view")} onClick={() => setView(r)}><Eye size={14} /></button></UiTooltip>{visibility.edit && <UiTooltip label="Edit"><button className={actionButtonClass("edit")} onClick={() => { setEditing(r); setForm({ province_id: String(r.province_id ?? ""), name: r.name ?? "", description: r.description ?? "" }); setShowForm(true); }}><Pencil size={14} /></button></UiTooltip>}<UiTooltip label="Audit"><button className={actionButtonClass("view")} onClick={() => setAudit(r)}><History size={14} /></button></UiTooltip>{buttons.map(([type, label, Icon, style]) => <UiTooltip key={type} label={label}><button className={actionButtonClass(style)} onClick={() => setAction({ type, row: r, label, remark: "" })}><Icon size={14} /></button></UiTooltip>)}</div>; } }];
  return <div className="pt-3 pb-6"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-widest text-blue-500">Settings / Master</p><h1 className="text-xl font-black text-slate-800">District</h1><p className="mt-1 text-xs font-medium text-slate-500">Manage districts under active provinces.</p></div>{canAdd && <button onClick={() => { setEditing(null); setForm(EMPTY); setShowForm(true); }} className="flex items-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white"><Plus size={14} /> Add district</button>}</div><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder="Search districts..." /><div className="mt-4"><DataTable columns={columns} rows={visible} isLoading={loading} rowKey={idOf} title="Districts" emptyTitle="No districts found" serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} /></div><DistrictForm open={showForm} form={form} setForm={setForm} provinces={provinces} editing={editing} saving={saving} onSave={save} onClose={() => { setShowForm(false); setEditing(null); }} />{view && <Modal open title="View district" onClose={() => setView(null)} size="sm"><dl className="grid gap-3 sm:grid-cols-2">{[["District", view.name], ["Province", provinces.find((p) => String(idOf(p)) === String(view.province_id))?.name ?? view.province_id], ["Description", view.description]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `District #${idOf(audit)}`} fields={[["name", "District"], ["province_id", "Province ID"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(auditPage, limit) => districtApi.audit({ id: idOf(audit), page: auditPage, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} district`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} onClose={close} onConfirm={() => void run()}>{action.type === "deauth" && <textarea placeholder="Rejection reason" value={action.remark} onChange={(e) => setAction({ ...action, remark: e.target.value })} className="mt-3 min-h-20 w-full rounded-xl border p-3" />}</ConfirmDialog>}</div>;
}
