import { useLiveChannel } from "@/Hooks/useLiveChannel";
import { API_ENDPOINTS } from "@/Utils/Constant";
import { getMakerCheckerButtons } from "@/Components/MakerChecker/buttonVisibility";
import { matchesAction } from "@/Utils/Lib/actionAliases";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Plus } from "lucide-react";
import { RowActions } from "@/Components/Common/RowActions";
import { useSelector } from "react-redux";
import { AuditModal } from "@/Components/Common/AuditModal";
import { mapAuditResponse } from "@/Components/Common/auditResponse";
import { ConfirmDialog } from "@/Components/Common/ConfirmDialog";
import { Spinner } from "@/Components/Common/Spinner";
import { PendingChangesDiff, usePendingChanges } from "@/Components/Common/PendingChangesDiff";
import { DataTable } from "@/Components/Common/DataTable";
import { Modal } from "@/Components/Common/Modal";
import { StatusFilterTabs, statusBucket } from "@/Components/Common/StatusFilterTabs";
import { StatusBadge } from "@/Components/MakerChecker/StatusBadge";
import { qualificationApi } from "@/Services/MasterConfig/district.api";
import { apiMessage, notifications } from "@/Utils/Lib/notifications";
import { useConfigLabel } from "@/Utils/I18n/configFieldLabels";

const empty = () => ({ name: "", description: "" });
const rowsOf = (r) => Array.isArray(r?.data) ? r.data : r?.data?.data ?? r?.data?.Qualification_array ?? [];
const idOf = (r) => r?.id ?? r?.Qualification_id;
const allowed = (menus, action) => (menus ?? []).some((m) => /Qualification/i.test(String(m?.menu_name)) && (m.actions ?? []).some((a) => matchesAction(a?.action_name ?? a?.name, action)));
function QualificationForm({ open, value, setValue, editing, saving, onClose, onSave }) { return <Modal open={open} onClose={onClose} title={editing ? "Edit Qualification" : "Add Qualification"} size="md" footer={<><button type="button" disabled={saving} onClick={onClose} className="px-3 py-2 text-sm font-bold text-muted-foreground">Cancel</button><button type="submit" form="Qualification-form" data-mode="draft" disabled={saving} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Save as draft</button><button type="submit" form="Qualification-form" data-mode="submit" disabled={saving} className="flex items-center justify-center gap-1.5 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white">{saving && <Spinner size={13} />}{saving ? "Saving..." : editing ? "Save changes" : "Add Qualification"}</button></>}><form id="Qualification-form" onSubmit={(e) => { e.preventDefault(); onSave(e.nativeEvent.submitter?.dataset?.mode === "draft"); }} className="grid gap-4"><label className="text-sm font-semibold text-slate-700">Qualification name<input required value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 outline-none focus:border-primary" /></label><label className="text-sm font-semibold text-slate-700">Description<textarea value={value.description} onChange={(e) => setValue({ ...value, description: e.target.value })} className="mt-1.5 min-h-24 w-full rounded-xl border border-border p-3 outline-none focus:border-primary" /></label></form></Modal>; }
export function Qualification() {
  const tr = useConfigLabel();
  const menus = useSelector((s) => s.menu.menuArray); const [page, setPage] = useState(1), [limit, setLimit] = useState(10), [rows, setRows] = useState([]), [pagination, setPagination] = useState({}), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [tab, setTab] = useState("all"), [form, setForm] = useState(empty), [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [view, setView] = useState(null), [audit, setAudit] = useState(null), [action, setAction] = useState(null), [saving, setSaving] = useState(false), [actionPending, setActionPending] = useState(false);
  const can = (a) => allowed(menus, a); const load = useCallback(async () => { setLoading(true); try { const r = await qualificationApi.list({ page, limit }); setRows(rowsOf(r)); setPagination(r?.pagination ?? r?.data?.pagination ?? {}); } catch (e) { notifications.error(e.message); } finally { setLoading(false); } }, [page, limit]); useEffect(() => { void load(); }, [load]);
  useLiveChannel(API_ENDPOINTS.MASTER_CONFIG.QUALIFICATION.LIST, () => void load());
  const pendingInfo = usePendingChanges(qualificationApi.pending, action ? idOf(action.row) : null, Boolean(action) && ["auth", "deauth", "deleteAuth"].includes(action?.type));
  const visible = useMemo(() => rows.filter((r) => (tab === "all" || statusBucket(r) === tab) && `${r.name ?? ""} ${r.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [rows, tab, search]);
  const save = async (isDraft) => { if (!form.name.trim()) return notifications.error("Qualification name is required"); setSaving(true); try { const p = { ...form, is_draft: isDraft, ...(editing ? { id: idOf(editing), expected_updated_time: editing.updated_time } : {}) }; const r = await (editing ? qualificationApi.edit(p) : qualificationApi.add(p)); notifications.success(apiMessage(r, "Qualification saved")); setOpen(false); setEditing(null); setForm(empty()); void load(); } catch (e) { notifications.error(e.message); } finally { setSaving(false); } };
  const run = async () => { setActionPending(true); try { const id = idOf(action.row); const r = action.type === "submit" ? await qualificationApi.submit({ id, narration: "Submitted for review" }) : action.type === "auth" ? await qualificationApi.auth({ id, narration: "approved" }) : action.type === "deauth" ? await qualificationApi.deauth({ id, narration: action.reason || "UNDEFINED" }) : action.type === "delete" ? await qualificationApi.delete({ id, narration: "Qualification no longer used" }) : action.type === "deactivate" ? await qualificationApi.deactivate({ id, narration: action.reason || "" }) : action.type === "reactivate" ? await qualificationApi.reactivate({ id, narration: action.reason || "" }) : await qualificationApi.deleteAuth({ id, narration: action.reason || "" }); notifications.success(apiMessage(r, "Qualification action completed")); setAction(null); void load(); } catch (e) { notifications.error(e.message); } finally { setActionPending(false); } };
  const columns = [{ key: "name", label: tr("Qualification"), align: "left", render: (r) => r.name ?? "-" }, { key: "description", label: tr("Description"), render: (r) => r.description ?? "-" }, { key: "status", label: tr("Status"), render: (r) => (r.status_name != null || r.status != null ? <StatusBadge status={String(r.status_name ?? (r.status === 1 ? "ACTIVE" : "INACTIVE"))} /> : "—") }, { key: "process_status_name", label: tr("Process Status"), render: (r) => (r.process_status_name ? <StatusBadge status={String(r.process_status_name)} /> : "—") }, { key: "auth_status", label: tr("Authorization Status"), render: (r) => (r.auth_status ? <StatusBadge status={String(r.auth_status)} /> : "—") }, { key: "actions", label: tr("Actions"), sortable: false, render: (r) => { const buttons = getMakerCheckerButtons(r, { canAdd: can("Add"), canEdit: can("Edit"), canAuthorize: can("Authorize"), canDelete: can("Delete") , canChangeStatus: can("Deactivate") || can("Reactivate")}); return <RowActions buttons={buttons} onView={() => setView(r)} onEdit={() => { setEditing(r); setForm({ name: r.name ?? "", description: r.description ?? "" }); setOpen(true); }} onAudit={() => setAudit(r)} onSubmit={() => setAction({ type: "submit", row: r, label: "Submit", reason: "" })} onAuthorize={() => setAction({ type: buttons.isPendingDelete ? "deleteAuth" : "auth", row: r, label: "Authorize", reason: "" })} onDeauthorize={() => setAction({ type: "deauth", row: r, label: "Deauthorize", reason: "" })} onDeactivate={() => setAction({ type: "deactivate", row: r, label: "Deactivate", reason: "" })} onReactivate={() => setAction({ type: "reactivate", row: r, label: "Reactivate", reason: "" })} onDelete={() => setAction({ type: "delete", row: r, label: "Delete", reason: "" })} />; } }];
  return <div className="pt-1 pb-6"><div className="mb-3 flex items-start justify-between"><div><h1 className="text-xl font-black text-slate-800">{tr("Qualification")}</h1><p className="mt-1 text-xs font-medium text-muted-foreground">{tr("Manage Qualification master data.")}</p></div></div><div className="overflow-hidden rounded-2xl" style={{ background: "var(--glass-bg)", backdropFilter: "blur(16px)", border: "1px solid var(--glass-border)", boxShadow: "var(--glass-shadow)" }}><StatusFilterTabs rows={rows} value={tab} onChange={setTab} search={search} onSearch={setSearch} searchPlaceholder={tr("Search Qualification...")} actions={can("Add") && <button onClick={() => { setEditing(null); setForm(empty()); setOpen(true); }} className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-bold text-white"><Plus size={14} /> {tr("Add")} {tr("Qualification")}</button>} bare /><DataTable columns={columns} rows={visible} rowKey={idOf} isLoading={loading} title={tr("Qualifications")} emptyTitle={tr("No Qualifications found")} serverPagination={{ page, totalPages: pagination.totalPages ?? 1, totalRecords: pagination.totalRecords ?? rows.length, onPageChange: setPage, limit, onLimitChange: (next) => { setLimit(next); setPage(1); } }} bare /></div><QualificationForm open={open} value={form} setValue={setForm} editing={editing} saving={saving} onSave={save} onClose={() => { setOpen(false); setEditing(null); }} />{view && <Modal open title={tr("View Qualification")} onClose={() => setView(null)} size="sm"><dl className="grid gap-3">{[["Name", view.name], ["Description", view.description]].map(([l, v]) => <div key={l} className="rounded-xl border border-border p-3"><dt className="text-[10px] font-bold uppercase text-muted-foreground">{l}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{v || "-"}</dd></div>)}</dl></Modal>}{audit && <AuditModal title={audit.name ?? `Qualification #${idOf(audit)}`} fields={[["name", "Name"], ["description", "Description"]]} onClose={() => setAudit(null)} fetchAudit={(p, limit) => qualificationApi.audit({ id: idOf(audit), page: p, limit }).then(mapAuditResponse)} />}{action && <ConfirmDialog open title={`${action.label} Qualification`} description={action.row.name} confirmLabel={action.label} destructive={action.type.includes("delete")} pending={actionPending} onClose={() => setAction(null)} onConfirm={() => void run()}>{["auth", "deauth", "deleteAuth"].includes(action.type) && <PendingChangesDiff {...pendingInfo} />}<textarea value={action.reason ?? ""} onChange={(e) => setAction({ ...action, reason: e.target.value })} placeholder="Narration" className="mt-3 min-h-20 w-full rounded-xl border p-3" /></ConfirmDialog>}</div>;
}




